/**
 * Hotel owner self-service workspace.
 *
 * v79-6 拆分自 js/app/hotel-owner.js（14 行 minified）。原样保留代码，
 * 仅修正 import 路径上移一级。
 */

import {$,$$,api,post,patch,esc,text,date,status,title,field,modal,region,action,toast,state,login,session,csv} from '../../core.js'
import {recordCard} from '../../../ui/card.js';
import {attachmentPicker} from '../../attachments.js';
export async function render(el){
 if(!state.session?.hotel_owner){el.innerHTML=title('酒店自助台')+`<div class="panel"><h2>${'老板自助台'}</h2><p>${'经营账户由超管开好，再把能管的酒店分给你。已经绑上经营账户的玩家，进来直接开门。'}</p><button id="owner-login" class="primary">${'我是老板'}</button></div>`;$('#owner-login',el).onclick=async()=>{await login(false,'hotel_owner');await session();if(state.session?.hotel_owner)render(el);};return;}
 el.innerHTML=title('我的酒店')+`<div class="tabs"><button data-owner-tab="hotels" aria-selected="true">${'酒店资料'}</button><button data-owner-tab="rooms">${'房型与房价'}</button><button data-owner-tab="bookings">${'预订处理'}</button></div><div id="owner-body"></div>`;let tab='hotels',data;
 const refresh=()=>region($('#owner-body',el),()=>api('/api/hotel-owner'),(d,box)=>{data=d;draw(box);});
 function draw(box){const list=data[tab];box.innerHTML=`<div class="section-head"><h2>${tab==='hotels'?'酒店资料':tab==='rooms'?'房型与房价':'预订处理'}</h2><div class="actions compact"><button id="owner-refresh">${'重新载入'}</button>${tab==='rooms'&&data.hotels.length?`<button id="owner-new">＋ ${'新房型'}</button>`:''}</div></div>`+(list.length?`<div class="cards">${list.map(r=>recordCard({title:r.name||r.room_name||'#'+r.id,body:tab==='bookings'?`<p>${esc(r.player_username||r.name)} · ${esc(r.contact)}</p><p>${esc(r.in_date)} → ${esc(r.out_date)}</p>${status(r.status)}`:`<p>${text(r.description||'')}</p><p>${tab==='rooms'?'💎 '+r.price_per_night+' / '+'晚' :esc(r.address)}</p>${status(r.is_active?'active':'pending')}`,actions:`<button data-edit="${r.id}">${tab==='bookings'?'处理预订':'改一改'}</button><button data-history="${r.id}">${'操作记录'}</button>`})).join('')}</div>`:`<div class="empty">${data.hotels.length?'这儿还空着':'超管还没把酒店分给你，找他开一间。'}</div>`);
 $('#owner-refresh',box).onclick=refresh;$('#owner-new',box)?.addEventListener('click',()=>edit({}));$$('[data-history]',box).forEach(b=>b.onclick=()=>action(b,async()=>{const d=await api(`/api/hotel-owner?history=1&entity=${tab}&id=${b.dataset.history}`);modal('谁动过这条',`<div class="wide">${d.events.map(e=>`<div class="row"><b>${esc(e.actor_name)} #${e.actor_id}</b><p>${esc(({post:'新建',patch:'改动','db.insert':'存了一条','db.update':'改了这条','db.delete':'删掉这条'})[e.action]||e.action)} · ${date(e.created_at)}</p></div>`).join('')||'还没人动过'}</div>`);}));$$('[data-edit]',box).forEach(b=>b.onclick=()=>edit(list.find(r=>r.id===+b.dataset.edit)));
 }
 function edit(record){if(tab==='bookings'){modal('处理这条预订',`<div class="notice wide">${esc(record.room_name)} · ${esc(record.in_date)} → ${esc(record.out_date)}</div>`+field('status','这条预订','select',record.status,{options:[['pending','待确认'],['confirmed','已确认'],['completed','已入住'],['cancelled','已取消']]}),{submit:async d=>{await patch('/api/hotel-owner?entity=bookings&id='+record.id,d);await refresh();}});return;}
 const room=tab==='rooms';let picker;const content=(room?field('hotel_id','挂在哪家','select',record.hotel_id||data.hotels[0].id,{options:data.hotels.map(h=>[h.id,h.name])}):'')+field('name','名字','text',record.name||'')+(room?field('capacity','住几人','number',record.capacity||2,{min:1,max:6})+field('beds','床型','text',record.beds||'',{required:false})+field('price_per_night','一晚多少 💎','number',record.price_per_night||0,{min:0})+field('breakfast_included','含早餐','checkbox',record.breakfast_included??1):field('address','地址','text',record.address||'',{required:false}))+field('description','介绍','textarea',record.description||'',{required:false})+field('image_url','图片 URL（也能在下方传）','text',record.image_url||'',{required:false})+field('is_active','在营业','checkbox',record.is_active??1);
 const dialog=modal('改这条信息',content,{wide:true,submit:async d=>{const images=picker.files();if(images.length)d.image_url=images[0].url;await (record.id?patch(`/api/hotel-owner?entity=${tab}&id=${record.id}`,d):post('/api/hotel-owner?entity=rooms',d));picker.commit();await refresh();toast('存下了');}});picker=attachmentPicker(dialog,{purpose:'public-image',max:1});}
 $$('[data-owner-tab]',el).forEach(b=>b.onclick=()=>{tab=b.dataset.ownerTab;$$('[data-owner-tab]',el).forEach(x=>x.setAttribute('aria-selected',x===b));if(data)draw($('#owner-body',el));});await refresh();
}