/**
 * Knowledge admin (DengDeng FAQ) workspace.
 *
 * v79-6 拆分自 js/app/knowledge-admin.js（6 行 minified）。仅修正 import 路径。
 */

import {$,$$,api,post,patch,field,modal,esc,text,region,action,toast} from '../../core.js';
import {renderKnowledgeAdvanced} from './advanced.js';
export async function renderKnowledge(el){let cursor=null;el.innerHTML='<h2>灯灯的问答本</h2><p>把玩家真会问的问题和你核对过的答案写下来，启用后灯灯才敢说。考试资料和内部信息不会出现在这儿。</p><div class="actions"><button id="faq-add">新增问答</button><button id="faq-refresh">重新载入</button></div><div class="toolbar">'+field('faq-test','拿一个问题试试','text','',{required:false,maxlength:500})+'<button id="faq-test-button">看灯灯能答什么</button></div><div id="faq-test-result"></div><div id="faq-list"></div><button id="faq-next" hidden>下一页</button><details id="faq-advanced"><summary>更多：导入资料、考试规则和历史记录</summary><div id="faq-advanced-body"></div></details>';
 const load=()=>region($('#faq-list',el),()=>api('/api/admin/knowledge?audience=public'+(cursor?'&cursor='+cursor:'')),(d,box)=>{box.innerHTML=d.articles.map(r=>`<article class="panel"><h3>${esc(r.question)}</h3><p>${text(r.answer)}</p><div class="actions"><span class="badge">${r.status==='published'&&r.source_valid?'已启用':'未启用'}</span><button data-faq-edit="${r.id}">改一改</button><button data-faq-toggle="${r.id}">${r.status==='published'?'停用':'启用'}</button></div></article>`).join('')||'<p class="notice">问答本还是空的。先新增一条，或者展开下面的「更多」导入站点说明。</p>';$('#faq-next',el).hidden=!d.next_cursor;$('#faq-next',el).onclick=()=>{cursor=d.next_cursor;load();};$$('[data-faq-edit]',box).forEach(b=>b.onclick=()=>edit(d.articles.find(r=>r.id===+b.dataset.faqEdit)));$$('[data-faq-toggle]',box).forEach(b=>b.onclick=()=>{const r=d.articles.find(r=>r.id===+b.dataset.faqToggle);if(r.status==='published')action(b,async()=>{await patch('/api/admin/knowledge?id='+r.id,{revision:r.revision,action:'retract'});await load();});else edit(r,true);});});
 function edit(r={},enable=false){modal(r.id?'改这条问答':'新增问答',field('question','玩家会怎么问','textarea',r.question||'',{maxlength:1000})+field('answer','我核对过的答案','textarea',r.answer||'',{maxlength:4000})+field('enabled','启用它（内容我核过，可以给玩家用）','checkbox',enable||r.status==='published'),{wide:true,submit:async v=>{if(v.enabled&&r.id&&!r.source_valid)throw new Error('原始资料变了，先在「更多」里同步再启用');const values={question:v.question,title:v.question.slice(0,150),answer:v.answer,audience:'public',keywords:r.keywords||''};const saved=r.id?await patch('/api/admin/knowledge?id='+r.id,{...values,revision:r.revision}):await post('/api/admin/knowledge',values);if(v.enabled)await patch('/api/admin/knowledge?id='+saved.id,{revision:r.id?saved.revision:1,action:'publish',confirm_review:true});toast('问答存下了');await load();}});}
 $('#faq-add',el).onclick=()=>edit();$('#faq-refresh',el).onclick=()=>{cursor=null;load();};$('#faq-test-button',el).onclick=e=>action(e.currentTarget,async()=>{const d=await api('/api/admin/knowledge?action=test&q='+encodeURIComponent($('[name=faq-test]',el).value));$('#faq-test-result',el).innerHTML=d.articles.map(r=>`<div class="notice"><b>${esc(r.title)}</b><p>${text(r.answer)}</p></div>`).join('')||'<p class="notice">没搜到已启用且原始资料没变的问答，灯灯会请你转人工。</p>';});let advanced=false;$('#faq-advanced',el).ontoggle=()=>{if(!advanced&&$('#faq-advanced',el).open){advanced=true;renderKnowledgeAdvanced($('#faq-advanced-body',el));}};await load();
}