import {getOrCreateAiBot} from '../_shared/ai.js';
import {fail} from './request.js';
export const publicChat=r=>r?{id:r.id,status:r.status,auto_handoff:!!r.auto_handoff,revision:r.revision,needs_ticket:!!r.needs_ticket,ticket_summary:r.needs_ticket?r.ticket_summary:null,linked_ticket_id:r.linked_ticket_id,requested_at:r.requested_at}:null;
export function needsHuman(text){const t=String(text||'').trim();if(/(?:不要|不用|暂不|不想).{0,5}人工/.test(t))return false;if(/人工|找.*客服|找.*工作人员/.test(t))return true;if(/^(你好|您好|hi|hello|谢谢|感谢|thanks|好的|好|ok)[!！。,.，\s]*$/i.test(t))return false;if(/建市|建城|哪年成立|成立年份/.test(t))return false;if(/(?:如何|怎么).{0,8}(?:举报|投诉|反馈)/.test(t))return false;return true;}
export function sensitiveChat(text){return /投诉|举报/.test(String(text||''));}
export async function requestChat(c,p,{reason='请求人工协助',mode='manual'}={}){const db=c.env.DB,bot=await getOrCreateAiBot(c.env);const current=await db.prepare('SELECT * FROM support_chats WHERE player_id=?').bind(p.id).first();if(current&&current.status!=='closed')return {chat:publicChat(current),existing:true};
 const recent=(await db.prepare('SELECT content FROM direct_messages WHERE from_player_id=? AND to_player_id=? ORDER BY id DESC LIMIT 200').bind(p.id,bot.id).all()).results;const restricted=!!current?.requires_super||sensitiveChat(reason+' '+recent.map(m=>m.content).join(' '));
 const ack='🤖 已在当前聊天转人工，请在这里等候或补充说明。工作人员会直接在本会话回复你。';
 const r=await db.batch([db.prepare("INSERT INTO support_chats(player_id,reason,requires_super) VALUES(?,?,?) ON CONFLICT(player_id) DO UPDATE SET status='queued',assigned_admin_id=NULL,reason=excluded.reason,requires_super=excluded.requires_super,auto_handoff=1,needs_ticket=0,ticket_summary=NULL,linked_ticket_id=NULL,revision=revision+1,requested_at=datetime('now'),updated_at=datetime('now') WHERE support_chats.status='closed'").bind(p.id,reason.slice(0,500),restricted?1:0),db.prepare("INSERT INTO support_chat_events(chat_id,actor_type,actor_id,actor_name,action,details) SELECT id,?,?,?,?,? FROM support_chats WHERE player_id=? AND changes()=1").bind(mode==='automatic'?'system':'player',mode==='automatic'?null:p.id,mode==='automatic'?'灯灯':p.username,'requested',JSON.stringify({mode}),p.id),db.prepare("INSERT INTO direct_messages(from_player_id,to_player_id,content) SELECT ?,?,? WHERE changes()=1").bind(bot.id,p.id,ack),db.prepare("INSERT INTO audit_events(actor_type,actor_id,actor_name,action,resource_type,resource_id,http_status,details) SELECT ?,?,?,'support.chat_requested','support_chats',CAST(id AS TEXT),201,? FROM support_chats WHERE player_id=? AND changes()=1").bind(mode==='automatic'?'system':'player',mode==='automatic'?null:p.id,mode==='automatic'?'灯灯':p.username,JSON.stringify({mode}),p.id),db.prepare("INSERT INTO notification_log(player_id,type,title,body,link) SELECT p.id,'support_chat','有玩家等待人工客服','请在后台人工客服聊天中接入会话。','/admin-v37.html#support' FROM admins a JOIN players p ON p.id=a.linked_player_id AND p.linked_admin_id=a.id WHERE p.id!=? AND (?=0 OR a.role='super') AND p.status='active' AND changes()=1").bind(p.id,restricted?1:0)]);
 const saved=await db.prepare('SELECT * FROM support_chats WHERE player_id=?').bind(p.id).first();if(!saved)fail(503,'转人工暂未成功，请重试');return {chat:publicChat(saved),existing:!r[0].meta.changes};
}
export async function chatAccess(db,a,id){const chat=await db.prepare('SELECT * FROM support_chats WHERE id=?').bind(id).first();if(!chat)fail(404,'会话不存在');if(a.linked_player_id===chat.player_id)fail(403,'不能处理自己的客服会话');if(chat.requires_super&&a.role!=='super')fail(403,'该会话仅限超管处理');return chat;}
