// Development only. Isolated SQLite database; no production bindings or secrets are read.
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {fileURLToPath} from 'node:url';
import {database,dispatch} from './local-d1.mjs';import {ensureDatabase} from '../functions/_core/database.js';import {hashPassword} from '../functions/_shared/auth.js';
const root=fileURLToPath(new URL('../',import.meta.url)),dir=fs.mkdtempSync(path.join(os.tmpdir(),'light-city-v51-')),DB=database(path.join(dir,'dev.sqlite'));await ensureDatabase(DB);
const {hash,salt}=await hashPassword('LocalTest51!');await DB.prepare("INSERT INTO admins(username,password_hash,salt,role) VALUES('qa-admin',?,?,'super')").bind(hash,salt).run();for(const u of ['qa-citizen','qa-neighbor'])await DB.prepare("INSERT INTO players(username,email,password_hash,salt,status,emeralds,bio) VALUES(?,?,?,?,'active',100,'本地测试账号，仅用于重写验收')").bind(u,u+'@example.invalid',hash,salt).run();
await DB.prepare('UPDATE admins SET linked_player_id=2 WHERE id=1').run();
await DB.prepare('UPDATE players SET linked_admin_id=1 WHERE id=2').run();
await DB.prepare("INSERT INTO hotel_owners(username,password_hash,salt,linked_player_id,created_by) VALUES('qa-owner',?,?,1,1)").bind(hash,salt).run();
await DB.prepare("INSERT INTO hotels(name,address,description,image_url) VALUES('本地测试 · 树上酒店','樱花林车站旁','用于本地验收的测试酒店','/assets/backgrounds/bg-pixel-hero.jpg')").run();
await DB.prepare('UPDATE hotels SET owner_id=1 WHERE id=1').run();
for(const [name,cap,price] of [['树影双床房',2,20],['林间家庭房',4,35],['观景单人房',1,12]])await DB.prepare("INSERT INTO hotel_rooms(hotel_id,name,capacity,beds,price_per_night,description) VALUES(1,?,?,'木制床铺',?,'本地测试房型，提交不会进入线上系统')").bind(name,cap,price).run();
await DB.prepare("INSERT INTO race_tracks(name,length_km,laps,trial_price,description) VALUES('本地测试 · 国际赛道',2.4,3,5,'双车道冰面赛道')").run();
await DB.prepare("INSERT INTO announcements(title,content,created_by) VALUES('本地重写验收环境','此页面使用本机 SQLite 测试数据，不会向线上数据库写入。',1)").run();
for(const [num,name,file] of [[1,'城市鸟瞰','06-overview-aerial.jpg'],[2,'樱花小屋','03-cherry-cabin.jpg'],[3,'城市轨道','07-railway.jpg']])await DB.prepare('INSERT INTO gallery_items(num,title,image_url) VALUES(?,?,?)').bind(num,name,'/assets/gallery/'+file).run();
await DB.prepare("INSERT INTO exam_questions(grade,q_type,question,options,answer,explanation) VALUES('B','choice','测试题：红灯时应该怎么做？','[\"停车等待\",\"加速通过\"]','A','这是用于验证答题流程的本地测试题。')").run();
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:8874');if(url.pathname==='/admin'||url.pathname==='/admin.html'){res.writeHead(302,{Location:'/admin-v37.html'});return res.end();}if(url.pathname.startsWith('/api/')){let body='';for await(const chunk of req)body+=chunk;const request=new Request(url,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:body});const response=await dispatch(request,{DB});const headers=Object.fromEntries(response.headers);if(headers['set-cookie'])headers['set-cookie']=headers['set-cookie'].replace('; Secure','');res.writeHead(response.status,headers);return res.end(Buffer.from(await response.arrayBuffer()));}
 let rel=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);if(!/^\/(?:assets\/|css\/|js\/|shared\/|[a-z0-9-]+\.(?:html|json|js)$)/i.test(rel)||rel.split('/').some(x=>x.startsWith('.'))) {res.writeHead(404);return res.end('Not found');}const f=path.resolve(root,'.'+rel);if(!f.startsWith(root)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end('Not found');}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.jpg':'image/jpeg','.woff2':'font/woff2'};res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(f).pipe(res);
 }catch(e){console.error(e);res.writeHead(500);res.end('Local server error');}});
server.listen(8874,'127.0.0.1',()=>console.log('Local: http://127.0.0.1:8874 | Isolated SQLite QA environment'));
process.on('SIGINT',()=>{server.close();DB.close();process.exit(0);});
