import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {api,esc,field,tr,state,status,imageUrl,linkUrl} from '../js/app/core.js';import {parseDate} from '../js/date.js';
const root=fileURLToPath(new URL('../',import.meta.url));const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
test('every frontend and backend module links; named imports exist',async()=>{for(const f of [...walk(root+'js'),...walk(root+'functions')].filter(f=>f.endsWith('.js'))){const cache=new Map(),get=p=>{if(!cache.has(p))cache.set(p,new vm.SourceTextModule(fs.readFileSync(p,'utf8'),{identifier:p}));return cache.get(p);};await assert.doesNotReject(()=>get(f).link((s,m)=>get(path.resolve(path.dirname(m.identifier),s.split('?')[0]))),f);}});
test('one shared entry and stylesheet power all seven pages, with no theme toggle',()=>{for(const page of ['index','hotel','profile','dm','notifications','admin-v37','hotel-owner','affairs','map','messages']){const html=fs.readFileSync(root+page+'.html','utf8');assert.match(html,/color-scheme" content="light"/);assert.match(html,/js\/app\/entry.js\?v=51/);assert.match(html,/css\/style.css\?v=51/);assert.doesNotMatch(html,/theme\.js|themeToggle|prefers-color-scheme|style.min.css/);for(const m of html.matchAll(/(?:src|href)="(\/[^"#?]+)(?:\?[^"#]*)?"/g)){if(m[1]==='/')continue;assert.ok(fs.existsSync(root+m[1].slice(1)),m[1]);}}const css=fs.readFileSync(root+'css/style.css','utf8');assert.doesNotMatch(css,/prefers-color-scheme|data-theme.*dark|themeToggle/);assert.match(css,/@media\(max-width:700px\)/);assert.match(css,/:focus-visible/);});
test('text and generated fields escape account-controlled strings',()=>{assert.equal(esc('<img src=x onerror=evil()>'),'&lt;img src=x onerror=evil()&gt;');const html=field('title','Title','text','" onfocus="bad');assert.doesNotMatch(html,/value="" onfocus/);assert.match(html,/&quot;/);});
test('imageUrl guards null / blank values and still whitelists safe URLs',()=>{/* Regression: an announcement / room with a missing image_url used to flow through linkUrl(null), which `new URL(null, location.href)` parsed as /null and returned as a real http(s) URL. The <img> rendered src="/null" and 404'd. */const prevLocation=globalThis.location;Object.defineProperty(globalThis,'location',{value:{href:'https://light-city.test/'},configurable:true});try{assert.equal(imageUrl(null),'');assert.equal(imageUrl(undefined),'');assert.equal(imageUrl(''),'');assert.equal(imageUrl('   '),'');assert.equal(imageUrl('\t\n'),'');assert.equal(imageUrl('/assets/backgrounds/bg-pixel-hero.jpg'),'https://light-city.test/assets/backgrounds/bg-pixel-hero.jpg');assert.equal(imageUrl('https://example.test/x.png'),'https://example.test/x.png');assert.equal(imageUrl('http://example.test/x.png'),'http://example.test/x.png');assert.equal(imageUrl('data:image/png;base64,iVBORw0KGgo='),'data:image/png;base64,iVBORw0KGgo=');assert.equal(imageUrl('data:image/webp;base64,UklGRg=='),'data:image/webp;base64,UklGRg==');assert.equal(imageUrl('data:image/svg+xml;base64,PHN2Zy8+'),'');assert.equal(imageUrl('javascript:alert(1)'),'');assert.equal(imageUrl('  https://example.test/x.png  '),'https://example.test/x.png');assert.equal(linkUrl('javascript:alert(1)'),'');assert.equal(linkUrl('  javascript:alert(1)  '),'');}finally{Object.defineProperty(globalThis,'location',{value:prevLocation,configurable:true});}});
test('all failed API writes reject, malformed responses never count as success',async()=>{const original=globalThis.fetch;try{for(const code of [401,403,409,500]){globalThis.fetch=async()=>new Response(JSON.stringify({ok:false,error:'test failure'}),{status:code});for(const method of ['GET','POST','PATCH','DELETE'])await assert.rejects(()=>api('/api/test',{method,body:method==='GET'?undefined:{}}),/test failure/);}globalThis.fetch=async()=>new Response('<html>Error</html>',{status:200});await assert.rejects(()=>api('/api/test'));}finally{globalThis.fetch=original;}});
test('language and status helpers work without shadowed translation state',()=>{state.language='en';assert.equal(tr('保存','Save'),'Save');assert.match(status('pending'),/Pending/);state.language='zh-CN';assert.match(status('pending'),/待审核/);});
test('SQLite and ISO dates normalize without NaN or duplicate timezone suffix',()=>{for(const s of ['2026-09-08 04:00:00','2026-09-08T04:00:00Z','2026-09-08T12:00:00+08:00'])assert.equal(parseDate(s).toISOString(),'2026-09-08T04:00:00.000Z');assert.ok(Number.isNaN(+parseDate('invalid')));});
test('service worker never intercepts HTML, auth or API responses',()=>{const handlers={};vm.runInNewContext(fs.readFileSync(root+'sw.js','utf8'),{URL,self:{location:{origin:'https://test.invalid'},addEventListener:(k,f)=>handlers[k]=f}});for(const url of ['/','/api/login','/api/admin/dashboard','/profile.html','/js/app/core.js']){let called=false;handlers.fetch({request:{url:'https://test.invalid'+url,method:'GET'},respondWith(){called=true;}});assert.equal(called,false,url);}});
test('copy-lock: every file in COPY_LOCK.json is byte-identical to its recorded SHA-256',()=>{/* Apple-motion second pass freezes the HTML, JS and local seed data so the
     user can compare visible copy against the v56 / 17c38fb baseline. Any
     edit to one of these files is a contract break. The CSS is not locked
     (it is the only file the second pass is allowed to rewrite).

     The only narrow exception: js/app/entry.js may carry ONE additional
     line at the very top — `import './press-motion.js';` — to wire the
     pure-visual press motion module in. The recorded hash in
     COPY_LOCK.json is for the file WITHOUT that line; the test below
     strips that single line before hashing so the on-disk entry.js can
     be exactly the locked hash + one allowed line. Any other change to
     entry.js still fails.                                                */
const manifestPath=root+'COPY_LOCK.json';assert.ok(fs.existsSync(manifestPath),'COPY_LOCK.json must exist at the workspace root');const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));assert.ok(manifest&&manifest.files&&typeof manifest.files==='object','COPY_LOCK.json must declare a files object');const entries=Object.entries(manifest.files);assert.ok(entries.length>0,'COPY_LOCK.json must list at least one file');const mismatches=[];const missing=[];const allowedImportLine=/^import\s+['"]\.\/press-motion\.js['"];?\s*$/m;for(const [rel,expected] of entries){const abs=root+rel;if(!fs.existsSync(abs)){missing.push(rel);continue;}let bytes=fs.readFileSync(abs);if(rel==='js/app/entry.js'){const src=bytes.toString('utf8');const lines=src.split('\n');/* The line must be at the very top, exactly one occurrence, exactly
   the allowed form. Any extra import is rejected.                       */
const importLines=lines.filter(l=>l.match(allowedImportLine));assert.ok(importLines.length<=1,'js/app/entry.js may contain at most one `import "./press-motion.js"` line; found '+importLines.length);assert.ok(importLines.length===1,'js/app/entry.js must contain the single allowed `import "./press-motion.js"` line at the top');assert.ok(lines[0].match(allowedImportLine),'the allowed import must be on the first line of js/app/entry.js (the only one-line modification permitted by the brief)');const normalized=src.replace(allowedImportLine,'').replace(/^\n+/,'');bytes=Buffer.from(normalized,'utf8');}const actual=crypto.createHash('sha256').update(bytes).digest('hex');if(actual!==expected)mismatches.push(`${rel}: expected ${expected}, got ${actual}`);}assert.deepEqual(missing,[],'COPY_LOCK.json references files that no longer exist on disk: '+missing.join(', '));assert.deepEqual(mismatches,[],'COPY_LOCK.json content drift detected (any change to a locked file is a contract break):\n'+mismatches.join('\n'));});
test('copy-lock: motion accessibility guarantees survive approved feature changes',()=>{/* Reinforces the second-pass scope: only css/style.css and css/style.min.css
     are mutable. UI_REVIEW.md, the new copy-lock test, and the motion brief
     are additive (untracked) and the front-end manifest test above checks
     everything in COPY_LOCK.json.                                          */const css=fs.readFileSync(root+'css/style.css','utf8');assert.match(css,/@media\s*\(prefers-reduced-motion:\s*reduce\)/,'prefers-reduced-motion fallback must be present in the second-pass stylesheet');assert.doesNotMatch(css,/@keyframes\s+(panel-in|dot-bounce|skeleton-shine|shake|bubble-in)/,'decorative / global entrance keyframes were removed in the second pass');});
test('copy-preservation: CSS never re-cases letters or injects new copy',()=>{/* User constraint (AGENTS.md top + APPLE_MOTION_BRIEF.md): existing text
     must remain verbatim. CSS must not change case nor inject characters.
     The first round kept `text-transform: uppercase` on .eyebrow, which
     silently upper-cased dynamic hotel names (and any other .eyebrow host)
     supplied by the data layer. This test rejects any case-folding CSS
     transformation and any `content: "..."` payload that adds alphabetic
     or CJK glyphs.                                                       */const cssRaw=fs.readFileSync(root+'css/style.css','utf8');/* Strip /* ... * / blocks so a literal word inside a comment is not picked
     up as a declaration. We keep block lengths so line offsets stay sane. */
const css=cssRaw.replace(/\/\*[\s\S]*?\*\//g,m=>m.replace(/[^\n]/g,' '));
const transforms=[...css.matchAll(/(?:^|[\s;{])text-transform\s*:\s*([^;}\n]+)/g)].map(m=>m[1].trim().toLowerCase());
assert.deepEqual(transforms,[],'CSS must not declare any text-transform. Found: '+transforms.join(', '));
const contents=[...css.matchAll(/(?:^|[\s;{])content\s*:\s*([^;}\n]+)/g)].map(m=>m[1].trim());
assert.ok(contents.length>0,'at least one `content: ...` declaration is expected (the page uses pseudo-element markers)');
for(const value of contents){
  const unquoted=value.replace(/^['"]|['"]$/g,'');
  const hasAlpha=/[A-Za-z]/.test(unquoted);
  const hasCJK=/[㐀-鿿]/.test(unquoted);
  assert.ok(!(hasAlpha||hasCJK),'CSS `content: '+value+'` would inject user-visible text (letters or CJK). Only neutral markers (e.g. "▸", "", "·") are allowed.');
}
});
test('toast centring survives prefers-reduced-motion',()=>{/* Under reduced-motion we set transform: none, which would cancel any
     centring done via translateX(-50%). The toast must still be centred
     purely by the box model. This test parses the .toast rule and asserts
     that the only animated transform is a Y offset and centring does not
     depend on translateX.                                                 */const css=fs.readFileSync(root+'css/style.css','utf8');const rule=css.match(/\.toast\s*\{[^}]*\}/);assert.ok(rule,'.toast rule must be present in the stylesheet');const block=rule[0];assert.match(block,/left\s*:\s*16px/,'.toast must use left inset for centring');assert.match(block,/right\s*:\s*16px/,'.toast must use right inset for centring');assert.match(block,/width\s*:\s*fit-content/,'.toast must size to its own content so inset+auto margins centre it');assert.match(block,/margin-left\s*:\s*auto/,'.toast must centre with auto inline margins');assert.match(block,/margin-right\s*:\s*auto/,'.toast must centre with auto inline margins');assert.doesNotMatch(block,/translateX\(-50%\)/,'.toast must not rely on translateX(-50%) for centring, because reduced-motion forces transform:none and the toast would shift left');const keyframesStart=css.indexOf('@keyframes toast-in');assert.ok(keyframesStart>=0,'@keyframes toast-in must exist');/* Brace-balanced slice: walk forward counting { and } so the inner
     "from { ... } to { ... }" is captured in full.                     */
let depth=0,end=keyframesStart;let inBody=false;for(let i=keyframesStart;i<css.length;i++){const ch=css[i];if(ch==='{'){depth++;inBody=true;}else if(ch==='}'){depth--;if(inBody&&depth===0){end=i+1;break;}}}const keyframes=css.slice(keyframesStart,end);assert.ok(end>keyframesStart,'@keyframes toast-in body parsed');assert.match(keyframes,/translateY\(8px\)/,'toast-in must animate the Y offset');assert.doesNotMatch(keyframes,/translateX\(/,'toast-in must not animate X — centring is the box model’s job');});
