import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {database,dispatch} from './local-d1.mjs';
import {ensureDatabase} from '../functions/_core/database.js';
import {hashPassword} from '../functions/_shared/auth.js';
const DB=database(),env={DB};let playerCookie,adminCookie,otherCookie,regularCookie;const pw='test-only-password';
async function call(path,method='GET',data,cookie){const r=await dispatch(new Request('https://local.test/api/'+path,{method,headers:{...(data?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},body:data===undefined?undefined:JSON.stringify(data)}),env);return {status:r.status,body:await r.json(),cookie:r.headers.get('Set-Cookie')?.split(';')[0]};}
before(async()=>{await ensureDatabase(DB);await DB.prepare("UPDATE dispatch_settings SET enabled=0 WHERE id=1").run();const {hash,salt}=await hashPassword(pw);for(const [u,role] of [['root','super'],['staff','admin']])await DB.prepare('INSERT INTO admins(username,password_hash,salt,role) VALUES(?,?,?,?)').bind(u,hash,salt,role).run();for(const u of ['alice','bob'])await DB.prepare("INSERT INTO players(username,email,password_hash,salt,status,emeralds) VALUES(?,?,?,?,'active',100)").bind(u,u+'@example.invalid',hash,salt).run();adminCookie=(await call('login','POST',{username:'root',password:pw,target:'admin'})).cookie;regularCookie=(await call('login','POST',{username:'staff',password:pw,target:'admin'})).cookie;playerCookie=(await call('login','POST',{username:'alice',password:pw})).cookie;otherCookie=(await call('login','POST',{username:'bob',password:pw})).cookie;});
after(()=>DB.close());
test('schema migration is repeatable and preserves records',async()=>{await ensureDatabase(DB);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM players').first()).n,2);assert.ok((await DB.prepare('PRAGMA table_info(kart_signups)').all()).results.some(c=>c.name==='status'));});
test('authentication and protected admin routes reject wrong identities',async()=>{assert.equal((await call('login')).status,401);assert.equal((await call('admin/dashboard','GET',undefined,playerCookie)).status,403);assert.equal((await call('admin/race-tracks','POST',{name:'x'},regularCookie)).status,403);assert.equal((await call('login','POST',{username:'root',password:'bad'})).status,401);assert.equal((await call('login','GET',undefined,playerCookie)).body.player.username,'alice');});
test('dashboard reads all schema-backed counts including empty race tables',async()=>{const r=await call('admin/dashboard','GET',undefined,adminCookie);assert.equal(r.status,200);assert.equal(r.body.players.active,2);assert.equal(r.body.kart.pending,0);assert.equal(r.body.circuit.pending,0);});
test('CRUD creates valid tracks, hotels and rooms; invalid fields fail before writes',async()=>{assert.equal((await call('admin/race-tracks','POST',{name:'测试赛道',trial_price:8,length_km:1.5},adminCookie)).status,201);assert.equal((await call('admin/hotels','POST',{name:'测试酒店'},adminCookie)).status,201);assert.equal((await call('admin/hotel-rooms','POST',{hotel_id:1,name:'双人房',capacity:2,price_per_night:20},adminCookie)).status,201);assert.equal((await call('admin/hotel-rooms','POST',{hotel_id:999,name:'错误房型'},adminCookie)).status,404);assert.equal((await call('admin/race-tracks','PATCH',{trial_price:-1},adminCookie)).status,400);assert.equal((await call('admin/hotels','DELETE',undefined,adminCookie)).status,400);});
test('booking uses numeric IDs and atomically creates one ticket',async()=>{const inDate=new Date(Date.now()+86400000*3).toISOString().slice(0,10),outDate=new Date(Date.now()+86400000*5).toISOString().slice(0,10);const data={room_id:1,room_name:'fake',in_date:inDate,out_date:outDate,persons:2,contact:'test@example.invalid'};assert.equal((await call('bookings','POST',data,playerCookie)).status,201);assert.equal((await call('bookings','POST',{...data,persons:3},playerCookie)).status,400);assert.equal((await call('bookings','POST',data,adminCookie)).status,401);const row=await DB.prepare('SELECT * FROM bookings').first();assert.equal(row.room_name,'双人房');assert.equal(row.name,'alice');assert.equal((await DB.prepare("SELECT COUNT(*) AS n FROM tickets WHERE source_table='bookings'").first()).n,1);assert.equal((await call('admin/hotel-rooms?id=1','DELETE',undefined,adminCookie)).status,409);});
test('circuit signup charges balance without overdraft and records the correct ticket source',async()=>{const data={track_id:1,license:'B',contact:'test@example.invalid'};const r=await call('circuit','POST',data,playerCookie);assert.equal(r.status,201);assert.equal((await DB.prepare("SELECT emeralds FROM players WHERE username='alice'").first()).emeralds,92);await DB.prepare("UPDATE players SET emeralds=0 WHERE username='alice'").run();assert.equal((await call('circuit','POST',data,playerCookie)).status,402);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM circuit_signups').first()).n,1);});
test('sign-in rewards once and never overwrites existing balance',async()=>{const r=await call('init?action=signin','POST',{},playerCookie);assert.equal(r.status,200);assert.equal(r.body.today_emeralds,1);assert.equal((await call('init?action=signin','POST',{},playerCookie)).status,409);assert.equal((await DB.prepare("SELECT emeralds FROM players WHERE username='alice'").first()).emeralds,1);});
test('messages are not duplicated in tickets and admin replies update the public source',async()=>{const m=await call('messages','POST',{type:'建议',content:'真实 SQL 测试',contact:'test@example.invalid'},playerCookie);assert.equal(m.status,201);const list=await call('tickets?category=message','GET',undefined,adminCookie);assert.equal(list.body.tickets.length,1);const id=list.body.tickets[0].id;const r=await call('tickets?id='+id,'PATCH',{status:'resolved',admin_reply:'已处理'},adminCookie);assert.equal(r.status,200);assert.equal((await DB.prepare('SELECT admin_reply FROM messages WHERE id=?').bind(m.body.id).first()).admin_reply,'已处理');assert.equal((await call('tickets?my=1','GET',undefined,otherCookie)).body.tickets.length,0);});
test('DM and notification data remains private to each account',async()=>{const r=await call('social?action=dm-send','POST',{to_username:'bob',content:'hello'},playerCookie);assert.equal(r.status,201);const list=await call('social?action=dm-list','GET',undefined,otherCookie);assert.equal(list.body.conversations[0].peer.username,'alice');const notif=await call('notifications?my=1','GET',undefined,otherCookie);assert.ok(notif.body.notifications.length>0);assert.equal((await call('notifications?id='+notif.body.notifications[0].id,'PATCH',{},playerCookie)).status,404);assert.equal((await call('notifications?id='+notif.body.notifications[0].id,'PATCH',{},otherCookie)).status,200);});
test('foreign origins and malformed JSON are rejected',async()=>{const r=await dispatch(new Request('https://local.test/api/messages',{method:'POST',headers:{Origin:'https://evil.invalid',Cookie:playerCookie},body:'{}'}),env);assert.equal(r.status,403);const bad=await dispatch(new Request('https://local.test/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:'null'}),env);assert.equal(bad.status,400);});

test('passkey schema, list format and ownership guards match the cryptographic adapter',async()=>{const start=await call('init?action=passkey-register-start','POST',{},playerCookie);assert.equal(start.status,200);assert.equal(start.body.publicKey.authenticatorSelection.userVerification,'required');assert.equal((await call('init?action=passkey-list','POST',{},playerCookie)).body.passkeys.length,0);await DB.prepare("INSERT INTO passkeys(player_id,name,credential_id,public_key_jwk) VALUES(2,'test','fixture-key','{}')").run();assert.equal((await call('init?action=passkey-delete','POST',{id:1},playerCookie)).status,404);assert.equal((await call('init?action=passkey-delete','POST',{id:1},otherCookie)).status,200);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM passkeys').first()).n,0);});
test('account linking is bidirectional and rejects conflicting relationships',async()=>{assert.equal((await call('init?action=admin-merge-account','POST',{admin_id:1,player_id:1},adminCookie)).status,200);assert.equal((await DB.prepare('SELECT linked_admin_id FROM players WHERE id=1').first()).linked_admin_id,1);assert.equal((await call('init?action=admin-merge-account','POST',{admin_id:2,player_id:1},adminCookie)).status,409);assert.equal((await call('init?action=admin-unmerge-account','POST',{admin_id:1,player_id:1},adminCookie)).status,200);assert.equal((await DB.prepare('SELECT linked_admin_id FROM players WHERE id=1').first()).linked_admin_id,null);});
test('administrator create, edit and reset guards validate before writes',async()=>{const r=await call('admin/admins','POST',{username:'newadmin',password:pw,role:'admin'},adminCookie);assert.equal(r.status,201);assert.equal((await call('admin/admins?id='+r.body.id,'PATCH',{new_password:pw},regularCookie)).status,403);assert.equal((await call('admin/admins?id='+r.body.id,'PATCH',{username:'rename-admin',role:'invalid',new_password:'AnotherTest51!'},adminCookie)).status,400);assert.equal((await DB.prepare('SELECT username FROM admins WHERE id=?').bind(r.body.id).first()).username,'newadmin');assert.equal((await call('admin/admins?id='+r.body.id,'DELETE',undefined,adminCookie)).status,200);});
test('announcements and question bank can be created and edited through real admin routes',async()=>{const r=await call('admin/announcements','POST',{title:'测试公告',content:'公告正文'},adminCookie);assert.equal(r.status,201);assert.equal((await call('admin/announcements?id='+r.body.id,'PATCH',{title:'更新公告'},adminCookie)).status,200);const q=await call('admin/exam-questions','POST',{grade:'B',q_type:'multi',question:'多选测试',options:['一','二','三'],answer:'AB',explanation:'答案解析'},adminCookie);assert.equal(q.status,201);const result=await call('exam-questions/answer','POST',{question_id:q.body.id,answer:'B|A'},playerCookie);assert.equal(result.body.is_correct,true);assert.equal((await call('exam-questions?grade=B','GET')).body.questions[0].answer,undefined);});
test('public homepage reads never recreate deleted tracks or insert default business records',async()=>{const before=await DB.prepare('SELECT COUNT(*) AS n FROM race_tracks').first();await call('homepage-bundle');await call('homepage-bundle');assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM race_tracks').first()).n,before.n);});
test('failing ticket insertion rolls the booking back',async()=>{const before=(await DB.prepare('SELECT COUNT(*) AS n FROM bookings').first()).n;await DB.prepare("CREATE TRIGGER fail_ticket BEFORE INSERT ON tickets BEGIN SELECT RAISE(ABORT,'test rollback'); END").run();const a=new Date(Date.now()+86400000*3).toISOString().slice(0,10),b=new Date(Date.now()+86400000*4).toISOString().slice(0,10);const result=await call('bookings','POST',{room_id:1,in_date:a,out_date:b,persons:1,contact:'test@example.invalid'},playerCookie);assert.equal(result.status,500);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM bookings').first()).n,before);await DB.prepare('DROP TRIGGER fail_ticket').run();});
test('concurrent check-ins yield exactly one reward',async()=>{const results=await Promise.all([call('init?action=signin','POST',{},otherCookie),call('init?action=signin','POST',{},otherCookie)]);assert.equal(results.filter(r=>r.status===200).length,1);assert.equal((await DB.prepare('SELECT emeralds FROM players WHERE id=2').first()).emeralds,101);});

test('concurrent license applications create only one pending request',async()=>{const data={exam_type:'written',contact:'test@example.invalid'};const results=await Promise.all([call('license','POST',data,playerCookie),call('license','POST',data,playerCookie)]);assert.equal(results.filter(r=>r.status===201).length,1);assert.equal((await DB.prepare("SELECT COUNT(*) AS n FROM license_signups WHERE player_id=1 AND exam_type='written'").first()).n,1);});
test('enabled announcement subscriptions receive notifications',async()=>{await call('subscriptions','POST',{type:'announcement',channel:'site'},otherCookie);await call('admin/announcements','POST',{title:'订阅推送测试',content:'这条只写入本地测试库'},adminCookie);assert.equal((await DB.prepare("SELECT COUNT(*) AS n FROM notification_log WHERE player_id=2 AND type='announcement'").first()).n,1);});

test('legacy production gallery columns migrate without losing images or draft status',async()=>{
 const legacy=database();try{
 await legacy.prepare("CREATE TABLE gallery_items(id INTEGER PRIMARY KEY AUTOINCREMENT,num INTEGER NOT NULL UNIQUE,cat TEXT NOT NULL,label TEXT NOT NULL,file_url TEXT NOT NULL,sort_order INTEGER DEFAULT 0,is_featured INTEGER DEFAULT 0,is_published INTEGER DEFAULT 1,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT)").run();
 await legacy.prepare("INSERT INTO gallery_items(num,cat,label,file_url,is_published) VALUES(1,'city','旧图集','https://example.invalid/old.jpg',1),(2,'kart','草稿','https://example.invalid/draft.jpg',0)").run();
 await ensureDatabase(legacy);
 const result=await dispatch(new Request('https://local.test/api/gallery'),{DB:legacy});assert.equal(result.status,200);const data=await result.json();assert.equal(data.items.length,1);assert.equal(data.items[0].title,'旧图集');assert.equal(data.items[0].image_url,'https://example.invalid/old.jpg');
 await legacy.prepare("INSERT INTO admins(username,password_hash,salt,role) VALUES('test','test','test','super')").run();await legacy.prepare("INSERT INTO sessions(token,admin_id,expires_at) VALUES('local-gallery-test',1,'2099-01-01T00:00:00Z')").run();
 const request=new Request('https://local.test/api/admin/gallery',{method:'POST',headers:{Cookie:'lc_session=local-gallery-test','Content-Type':'application/json'},body:JSON.stringify({num:3,title:'新图片',image_url:'https://example.invalid/new.jpg'})});
 const created=await dispatch(request,{DB:legacy});assert.equal(created.status,201);const row=await legacy.prepare('SELECT * FROM gallery_items WHERE num=3').first();assert.equal(row.label,'新图片');assert.equal(row.file_url,'https://example.invalid/new.jpg');assert.equal(row.is_published,1);
 }finally{legacy.close();}
});

test('legacy messages and comments without type or author_name remain readable',async()=>{
 const old=database();try{
 await old.prepare("CREATE TABLE messages(id INTEGER PRIMARY KEY,player_id INTEGER,name TEXT,contact TEXT,content TEXT,status TEXT DEFAULT 'unread',created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();
 await old.prepare("CREATE TABLE message_comments(id INTEGER PRIMARY KEY,message_id INTEGER,player_id INTEGER,content TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();
 await old.prepare("INSERT INTO messages(id,name,contact,content) VALUES(1,'旧市民','private@example.invalid','历史留言')").run();await old.prepare("INSERT INTO message_comments(id,message_id,content) VALUES(1,1,'历史评论')").run();
 await ensureDatabase(old);const r=await dispatch(new Request('https://local.test/api/messages?public=1'),{DB:old});assert.equal(r.status,200);const d=await r.json();assert.equal(d.messages[0].content,'历史留言');assert.equal(d.messages[0].comment_count,1);assert.equal(d.messages[0].contact,undefined);
 const c=await dispatch(new Request('https://local.test/api/comments?message_id=1'),{DB:old});assert.equal(c.status,200);assert.equal((await c.json()).comments[0].author_name,'市民');
 }finally{old.close();}
});

test('legacy bookings and license tables without status support dashboard statistics',async()=>{
 const old=database();try{
 await old.prepare("CREATE TABLE bookings(id INTEGER PRIMARY KEY,player_id INTEGER,state TEXT)").run();
 await old.prepare("CREATE TABLE license_signups(id INTEGER PRIMARY KEY,player_id INTEGER,exam_type TEXT,result TEXT)").run();
 await old.prepare("INSERT INTO bookings(id,state) VALUES(1,'confirmed')").run();
 await old.prepare("INSERT INTO license_signups(id,exam_type,result) VALUES(1,'written','passed'),(2,'road',NULL)").run();
 await ensureDatabase(old);
 await old.prepare("INSERT INTO admins(username,password_hash,salt,role) VALUES('test','x','x','super')").run();
 await old.prepare("INSERT INTO sessions(token,admin_id,expires_at) VALUES('stats-test',1,'2099-01-01T00:00:00Z')").run();
 const response=await dispatch(new Request('https://local.test/api/admin/dashboard',{headers:{Cookie:'lc_session=stats-test'}}),{DB:old});
 assert.equal(response.status,200);const d=await response.json();assert.equal(d.partial,false);assert.equal(d.bookings.confirmed,1);assert.equal(d.bookings.pending,0);assert.equal(d.license.passed,1);assert.equal(d.license.pending,1);
 }finally{old.close();}
});

test('one failed dashboard query preserves other statistics without inventing zero counts',async()=>{
 const {onRequestGet}=await import('../functions/api/admin/dashboard.js');
 const wrapped={prepare(sql){if(sql.includes('FROM bookings GROUP BY'))return {all:async()=>{throw new Error('test unavailable');}};return DB.prepare(sql);}};
 const response=await onRequestGet({env:{DB:wrapped},request:new Request('https://local.test/api/admin/dashboard',{headers:{Cookie:adminCookie}})});
 assert.equal(response.status,200);const d=await response.json();assert.equal(d.partial,true);assert.equal(d.bookings,null);assert.equal(d.players.active,2);assert.equal(d.errors.bookings.code,'STAT_QUERY_FAILED');
});
