import {test} from 'node:test';import assert from 'node:assert/strict';
import {database,dispatch} from './local-d1.mjs';import {ensureDatabase} from '../functions/_core/database.js';import {hashPassword} from '../functions/_shared/auth.js';
import {session,state} from '../js/app/core.js';
const encode=x=>Buffer.from(x).toString('base64url'),hash=async x=>new Uint8Array(await crypto.subtle.digest('SHA-256',x));
function der(raw){const parts=[raw.slice(0,32),raw.slice(32)].map(x=>{while(x.length>1&&x[0]===0)x=x.slice(1);if(x[0]&128)x=Buffer.concat([Buffer.from([0]),x]);return Buffer.concat([Buffer.from([2,x.length]),x]);});const body=Buffer.concat(parts);return Buffer.concat([Buffer.from([48,body.length]),body]);}
async function fixture(fn){const DB=database();try{await ensureDatabase(DB);const password='Test-only-passkey-56!',stored=await hashPassword(password);await DB.prepare("INSERT INTO admins(id,username,role,password_hash,salt,linked_player_id) VALUES(1,'manager','super',?,?,1),(2,'unlinked','admin',?,?,NULL)").bind(stored.hash,stored.salt,stored.hash,stored.salt).run();for(const [id,name,linked]of [[1,'citizen',1],[2,'neighbor',null]])await DB.prepare("INSERT INTO players(id,username,email,password_hash,salt,status,linked_admin_id) VALUES(?,?,?,?,?,'active',?)").bind(id,name,name+'@example.invalid',stored.hash,stored.salt,linked).run();for(const [token,p,a]of [['one',1,null],['two',2,null],['one-again',1,null],['old-admin',null,1],['unlinked-admin',null,2]])await DB.prepare("INSERT INTO sessions(token,player_id,admin_id,expires_at) VALUES(?,?,?,'2099-01-01T00:00:00Z')").bind(token,p,a).run();const keys=[];for(const [id,p,a]of [[1,1,1],[2,2,null],[3,null,1],[4,2,1]]){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),jwk=await crypto.subtle.exportKey('jwk',pair.publicKey),credId=encode(Buffer.from('test-key-'+id));keys[id]={...pair,credId};await DB.prepare("INSERT INTO passkeys(id,player_id,admin_id,credential_id,public_key_jwk,name) VALUES(?,?,?,?,?,?)").bind(id,p,a,credId,JSON.stringify(jwk),'本地测试密钥 '+id).run();}
 const call=async(action,data={},token='one',method='POST')=>{const r=await dispatch(new Request('https://local.test/api/'+action,{method,headers:{'Content-Type':'application/json',...(token?{Cookie:'lc_session='+token}:{})},body:method==='GET'?undefined:JSON.stringify(data)}),{DB});return {http:r.status,cookie:r.headers.get('Set-Cookie')?.split(';')[0],...await r.json()};};
 const sign=async(start,keyId=1,{origin='https://local.test',flags=5,count=1,type='webauthn.get',rp='local.test'}={})=>{const client=Buffer.from(JSON.stringify({challenge:start.publicKey.challenge,type,origin})),auth=Buffer.alloc(37);auth.set(await hash(Buffer.from(rp)),0);auth[32]=flags;auth.writeUInt32BE(count,33);const signed=Buffer.concat([auth,await hash(client)]),signature=Buffer.from(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},keys[keyId].privateKey,signed));return {challenge_token:start.challenge_token,credential:{id:keys[keyId].credId,rawId:keys[keyId].credId,type:'public-key',response:{clientDataJSON:encode(client),authenticatorData:encode(auth),signature:encode(der(signature))}}};};
 await fn({DB,call,sign,password,keys});}finally{DB.close();}}
test('passkey verification succeeds with a real ES256 signature without logging in or changing account',()=>fixture(async({DB,call,sign})=>{const start=await call('init?action=passkey-test-start',{id:1});assert.equal(start.http,200);const count=(await DB.prepare('SELECT COUNT(*) AS n FROM sessions').first()).n;const finish=await call('init?action=passkey-test-finish',await sign(start));assert.equal(finish.http,200);assert.equal(finish.verified,true);assert.equal(finish.cookie,undefined);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM sessions').first()).n,count);assert.equal((await call('login',{},'one','GET')).player.id,1);}));
test('verification offers only the selected owned key and rejects foreign credentials',()=>fixture(async({call,sign,keys})=>{assert.equal((await call('init?action=passkey-test-start',{id:2})).http,404);const start=await call('init?action=passkey-test-start',{id:1});assert.deepEqual(start.publicKey.allowCredentials.map(k=>k.id),[keys[1].credId]);assert.equal((await call('init?action=passkey-test-finish',await sign(start,2))).http,403);}));
test('verification is bound to the current session and cannot be replayed',()=>fixture(async({call,sign})=>{const start=await call('init?action=passkey-test-start',{id:1}),body=await sign(start);assert.equal((await call('init?action=passkey-test-finish',body,'one-again')).http,403);assert.equal((await call('init?action=passkey-test-finish',body)).http,200);assert.equal((await call('init?action=passkey-test-finish',body)).http,400);}));
test('origin, RP, device verification, challenge type and signature are validated',()=>fixture(async({call,sign})=>{for(const options of [{origin:'https://other.invalid'},{rp:'other.invalid'},{flags:1},{flags:4},{type:'webauthn.create'}]){const start=await call('init?action=passkey-test-start',{id:1});assert.equal((await call('init?action=passkey-test-finish',await sign(start,1,options))).http,400);}const start=await call('init?action=passkey-test-start',{id:1}),body=await sign(start);const bad=Buffer.from(body.credential.response.signature,'base64url');bad[bad.length-1]^=1;body.credential.response.signature=encode(bad);assert.equal((await call('init?action=passkey-test-finish',body)).http,400);}));
test('testing a key cannot be used as admin login proof',()=>fixture(async({call,sign})=>{const start=await call('init?action=passkey-test-start',{id:1});assert.equal((await call('init?action=passkey-admin-finish',await sign(start))).http,400);assert.equal((await call('admin/dashboard',{},'one','GET')).http,403);}));
test('admin passkey verification requires an active reciprocal player binding and creates a combined session',()=>fixture(async({call,sign,keys})=>{assert.equal((await call('init?action=passkey-admin-start',{},'two')).http,403);assert.equal((await call('init?action=passkey-admin-start',{},null)).http,401);const start=await call('init?action=passkey-admin-start');assert.deepEqual(start.publicKey.allowCredentials.map(k=>k.id),[keys[1].credId,keys[3].credId]);const finish=await call('init?action=passkey-admin-finish',await sign(start));assert.equal(finish.http,200);const token=finish.cookie.split('=')[1];const me=await call('login',{},token,'GET');assert.equal(me.admin.id,1);assert.equal(me.player.id,1);assert.equal((await call('login',{},'one','GET')).http,401);}));
test('unlinking during admin verification prevents elevation',()=>fixture(async({DB,call,sign})=>{const start=await call('init?action=passkey-admin-start');await DB.prepare('UPDATE players SET linked_admin_id=NULL WHERE id=1').run();assert.equal((await call('init?action=passkey-admin-finish',await sign(start))).http,403);}));
test('password-assisted admin login retains the player and leaving administration removes actual admin access',()=>fixture(async({call,password})=>{const enter=await call('init?action=admin-enter-password',{admin_password:password});assert.equal(enter.http,200);const token=enter.cookie.split('=')[1];assert.equal((await call('admin/dashboard',{},token,'GET')).http,200);const leave=await call('init?action=admin-logout',{},token);assert.equal(leave.player_retained,true);const me=await call('login',{},token,'GET');assert.equal(me.player.id,1);assert.equal(me.admin,null);assert.equal((await call('admin/dashboard',{},token,'GET')).http,403);}));
test('old administrator-only sessions return to a linked citizen or become logged out',()=>fixture(async({call})=>{assert.equal((await call('init?action=admin-logout',{},'old-admin')).player_retained,true);assert.equal((await call('login',{},'old-admin','GET')).player.id,1);assert.equal((await call('init?action=admin-logout',{},'unlinked-admin')).player_retained,false);assert.equal((await call('login',{},'unlinked-admin','GET')).http,401);}));
test('player password login cannot silently fall back to administrator identity',()=>fixture(async({call,password})=>{assert.equal((await call('login',{username:'manager',password,target:'player'},null)).http,401);assert.equal((await call('init?action=passkey-login-finish',{target:'admin'},null)).http,403);}));
test('public page session refresh leaves admin mode while administrator pages preserve it',async()=>{const fetch=globalThis.fetch,doc=globalThis.document;try{for(const page of ['home','admin']){globalThis.document={body:{dataset:{page}}};const calls=[];globalThis.fetch=async(url)=>{calls.push(url);const data=calls.length===1?{admin:{id:1},player:{id:1}}:calls.length===2?{}:{admin:null,player:{id:1}};return Response.json({ok:true,...data});};await session();assert.equal(calls.length,page==='home'?3:1);if(page==='home'){assert.equal(calls[1],'/api/init?action=admin-logout');assert.equal(state.session.admin,null);}}}finally{globalThis.fetch=fetch;if(doc===undefined)delete globalThis.document;else globalThis.document=doc;}});
