import {endpoint,identity,body,string,integer,reply,fail} from '../_core/request.js';
import {getOrCreateAiBot} from '../_shared/ai.js';
import {requestChat,publicChat} from '../_core/chat-support.js';
export const onRequestGet=c=>endpoint(async()=>{const p=await identity(c);return reply({chat:publicChat(await c.env.DB.prepare('SELECT * FROM support_chats WHERE player_id=?').bind(p.id).first())});});
export const onRequestPost=c=>endpoint(async()=>{const p=await identity(c),b=await body(c.request),db=c.env.DB;
 if(b.action==='cancel'){const chat=await db.prepare('SELECT * FROM support_chats WHERE player_id=?').bind(p.id).first();if(!chat||chat.status==='closed')return reply({ended:true});const bot=await getOrCreateAiBot(c.env);const r=await db.batch([db.prepare("UPDATE support_chats SET status='closed',auto_handoff=0,revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=? AND status IN ('queued','active')").bind(chat.id,integer(b.revision,'会话版本',1)),db.prepare("INSERT INTO support_chat_events(chat_id,actor_type,actor_id,actor_name,action) SELECT ?,'player',?,?,'ended_by_player' WHERE changes()=1").bind(chat.id,p.id,p.username),db.prepare("INSERT INTO direct_messages(from_player_id,to_player_id,content) SELECT ?,?,? WHERE changes()=1").bind(bot.id,p.id,'已结束本次人工等待或会话。聊天记录会保留，你可以继续与灯灯交流，需要时再手动转人工。')]);if(!r[0].meta.changes)fail(409,'客服状态已变化，请刷新后确认');return reply({ended:true});}
 if(b.action==='link-ticket'){const id=integer(b.ticket_id),chat=await db.prepare('SELECT * FROM support_chats WHERE player_id=? AND needs_ticket=1').bind(p.id).first();if(!chat)fail(403,'请先由人工客服建议提交工单');if(!await db.prepare('SELECT id FROM tickets WHERE id=? AND player_id=?').bind(id,p.id).first())fail(404,'工单不存在');if(chat.linked_ticket_id&&chat.linked_ticket_id!==id)fail(409,'该会话已关联工单');const result=await db.batch([db.prepare('UPDATE support_chats SET linked_ticket_id=?,revision=revision+1 WHERE id=? AND (linked_ticket_id IS NULL OR linked_ticket_id=?)').bind(id,chat.id,id),db.prepare("INSERT INTO support_chat_events(chat_id,actor_type,actor_id,actor_name,action,details) SELECT ?,'player',?,?,'ticket_linked',? WHERE changes()=1").bind(chat.id,p.id,p.username,JSON.stringify({ticket_id:id}))]);if(!result[0].meta.changes)fail(409,'该会话已关联其他工单，请刷新查看');return reply({linked:true});}
 const r=await requestChat(c,p,{reason:string(b.reason||'请求人工协助','说明',500)});return reply(r,r.existing?200:201);
});
