import {$,$$,api,region,tr,esc,date,status,empty,title,state,login,toast} from './core.js';
import {viewCitizenTicket} from './ticket-form.js';
export async function render(el){
 el.innerHTML=title('我的事务','My affairs');if(!state.session?.player){el.insertAdjacentHTML('beforeend','<section class="panel"><p>登录后查看自己的办理进度与提醒。</p><button id="affairs-login">市民登录</button></section>');$('#affairs-login',el).onclick=async()=>{await login();if(state.session?.player)await render(el);};return;}
 el.insertAdjacentHTML('beforeend',`<div class="affairs-workspace"><aside class="affairs-assistant panel"><div class="row-head"><h2>灯灯 · 个人小助手</h2><button id="affairs-refresh">刷新</button></div><p>为你汇总最近事务与当前提醒。数据在打开和刷新时更新。</p><div id="affairs-reminders" role="status"></div><div class="actions"><a class="button primary" href="/messages.html?to=${encodeURIComponent('灯灯客服')}">问灯灯我的近况</a><a class="button" href="/profile.html#security">账号与登录管理</a><a class="button" href="/map.html">城市地图与施工</a></div></aside><div class="affairs-records"><div class="tabs" id="affairs-filters">${[['all','全部'],['attention','需要我关注'],['ticket','工单'],['booking','酒店'],['exam','考试'],['support','人工客服']].map(([k,l])=>`<button data-filter="${k}" aria-selected="${k==='all'}">${l}</button>`).join('')}</div><section id="affairs-items" class="section"></section></div></div>`);
 let data,filter='all';const labels={ticket:'工单',booking:'酒店',exam:'考试',license:'驾照申请',appeal:'成绩复核',support:'客服'};
 function affairStatus(r){const labels=r.kind==='support'?{queued:'等待人工接入',active:'人工客服已接入',ended:'人工会话已结束'}:r.kind==='exam'?{generating:'生成试卷中',in_progress:'作答中',grading:'批改中',needs_review:'简答待复核',graded:'已批改',abandoned:'已放弃'}:{};return labels[r.status]?`<span class="badge">${labels[r.status]}</span>`:status(r.status);}
 function draw(){const rows=data.items.filter(r=>filter==='all'||filter==='attention'&&r.attention||r.kind===filter);$('#affairs-items',el).innerHTML=rows.map(r=>`<article class="panel"><div class="row-head"><h3>${esc(r.title)}</h3>${affairStatus(r)}</div><small>${labels[r.kind]} · ${date(r.created_at)}</small>${r.in_date?`<p>入住 ${esc(r.in_date)} — 离店 ${esc(r.out_date)}</p>`:''}${r.kind==='exam'?`<p>${r.score===null?'总分尚未确定':`成绩 ${Number(r.score)} 分`}</p>`:''}<div class="actions">${r.kind==='ticket'?`<button data-ticket="${esc(r.id)}">查看详情 / 补充与追问</button>`:`<a class="button" href="${esc(r.href)}">查看 / 继续办理</a>`}</div></article>`).join('')||empty('当前分类没有近期记录');$$('[data-ticket]',el).forEach(b=>b.onclick=()=>viewCitizenTicket(b.dataset.ticket,{onChanged:load}).catch(e=>toast(e.message,true)));}
 async function load(){await region($('#affairs-items',el),()=>api('/api/my-affairs'),d=>{data=d;$('#affairs-reminders',el).innerHTML=`<p>有 <b>${d.unread_count}</b> 条未读通知、<b>${d.items.filter(r=>r.attention).length}</b> 项值得关注的近期事务。<a href="/messages.html?tab=notifications">查看消息</a></p><small>更新于 ${date(d.as_of)} · 显示各类最近记录，完整历史可在相应页面查看。</small>`;draw();});}
 $$('[data-filter]',el).forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]',el).forEach(x=>x.setAttribute('aria-selected',x===b));if(data)draw();});$('#affairs-refresh',el).onclick=load;await load();
 const ticket=new URLSearchParams(location.search).get('ticket');if(ticket)await viewCitizenTicket(ticket,{onChanged:load});
}
