import {$,$$,api,tr,esc,date,field,modal,region,action,csv} from './core.js';
const actionNames={'dm-send':'发送私信','dm-read':'标记已读（历史记录）','ticket.human_request_checked':'检查已有人工请求','dm.auto_replied':'灯灯自动回复','ai.draft_created':'生成 AI 草稿（未发送）','ticket.auto_replied':'自动基础回复','ticket.human_requested':'请求转人工','ticket.player_followup':'市民补充说明','ticket.auto_assigned':'自动派单','ticket.auto_deferred':'自动派单暂缓','dispatch.policy_changed':'调整自动派单规则','post':'提交/创建','patch':'修改','delete':'删除','db.insert':'保存记录','db.update':'更新记录','db.delete':'删除记录','ticket.assigned':'派单','ticket.replied':'回复工单','ticket.status_changed':'工单状态','ticket.published':'公开处理','ticket.unpublished':'取消公开','ui.export':'导出数据'};
export function auditRows(events){return events.length?`<div class="table-wrap"><table><thead><tr><th>${tr('时间','Time')}</th><th>${tr('操作者','Actor')}</th><th>${tr('操作','Action')}</th><th>${tr('对象','Resource')}</th><th>${tr('结果','Result')}</th><th>${tr('明细','Details')}</th></tr></thead><tbody>${events.map(e=>`<tr><td>${date(e.created_at)}</td><td>${esc(tr(({system:'系统',admin:'管理员',player:'玩家',hotel_owner:'酒店老板',anonymous:'访客',applicant:'申请人'})[e.actor_type]||e.actor_type,e.actor_type))} #${e.actor_id||'—'} · ${esc(e.actor_name)}</td><td>${esc(tr(actionNames[e.action]||e.action,e.action))}</td><td>${esc(tr(({tickets:'工单',ticket_events:'办理记录',ticket_rewards:'办结奖励',players:'市民账号',admins:'管理员账号',hotel_owners:'酒店老板账号',hotels:'酒店',hotel_rooms:'房型',bookings:'预订',notification_log:'通知',media_uploads:'附件',direct_messages:'私信'})[e.resource_type]||e.resource_type,e.resource_type))} #${esc(e.resource_id||'—')}</td><td>${e.http_status||'—'}</td><td class="wrap">${esc(e.details||'')}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">${tr('暂无操作记录（查看和登录不记录）','No operation records; viewing and login are excluded')}</div>`;}
export async function viewAudit(resourceType,resourceId){const dialog=modal(tr('操作留痕','Operation history'),'<div class="wide" id="record-audit"></div>',{wide:true});await region($('#record-audit',dialog),()=>api('/api/admin/audit?resource_type='+encodeURIComponent(resourceType)+'&resource_id='+encodeURIComponent(resourceId)),(d,el)=>el.innerHTML=auditRows(d.events));}
export async function renderAudit(el){let snapshot=null,cursor=null;el.innerHTML=`<h2>${tr('操作留痕与导出','Operation audit & export')}</h2><p class="muted">${tr('仅记录实际业务操作及导出。查看页面和登录不记录；通用日志不包含密码、会话令牌或附件原文。','Business changes and exports only. Viewing and login are excluded; credentials and attachment content are not logged.')}</p><div class="toolbar">${field('from',tr('开始日期','From'),'date','',{required:false})}${field('to',tr('结束日期','To'),'date','',{required:false})}${field('actor_type',tr('身份','Actor type'),'select','',{required:false,options:[['',tr('全部','All')],['player',tr('玩家','Citizen')],['admin',tr('管理员','Administrator')],['hotel_owner',tr('酒店老板','Hotel owner')],['system',tr('系统 / 灯灯','System / DengDeng')]]})}${field('actor_id',tr('账号编号','Account ID'),'number','',{required:false,min:1})}<button id="audit-refresh">${tr('查询','Search')}</button><button id="audit-export">${tr('导出全部筛选结果','Export all filtered records')}</button></div><div id="audit-rows"></div><button id="audit-next" hidden>${tr('下一页','Next page')}</button>`;
 const query=()=>{const p=new URLSearchParams();$$('[name]',el).forEach(e=>{if(e.value)p.set(e.name,e.value);});return p;};
 const load=()=>region($('#audit-rows',el),()=>{const q=query();if(snapshot!==null)q.set('snapshot',snapshot);if(cursor)q.set('cursor',cursor);return api('/api/admin/audit?'+q);},(d,box)=>{snapshot=d.snapshot;cursor=d.next_cursor;box.innerHTML=auditRows(d.events);$('#audit-next',el).hidden=!cursor;});
 $('#audit-refresh',el).onclick=()=>{snapshot=null;cursor=null;load();};$('#audit-next',el).onclick=load;
 $('#audit-export',el).onclick=e=>action(e.currentTarget,async()=>{const result=[];let next=null,cap=null;do{const q=query();q.set('limit','1000');if(cap!==null)q.set('snapshot',cap);if(next)q.set('cursor',next);const d=await api('/api/admin/audit?'+q);result.push(...d.events);cap=d.snapshot;next=d.next_cursor;}while(next);await csv('light-city-operation-audit.csv',result);});await load();
}
