import {tableFrame} from '../ui/table.js';
import {$,$$,api,esc,date,field,modal,region,action,csv} from './core.js'
const actionNames={'map.saved':'存了地点 / 施工状态','dm-send':'发了私信','dm-read':'标了已读（旧记录）','ticket.human_request_checked':'查过有没有人接手','dm.auto_replied':'灯灯自动回话','ai.draft_created':'AI 起了草稿（没发）','ticket.auto_replied':'自动基础回复','ticket.human_requested':'玩家要求转人工','ticket.player_followup':'玩家补了情况','ticket.auto_assigned':'自动派单','ticket.auto_deferred':'自动派单先按住','dispatch.policy_changed':'改了派单规矩','post':'新建','patch':'改','delete':'删','db.insert':'写入记录','db.update':'更新记录','db.delete':'删掉记录','ticket.assigned':'派单','ticket.replied':'回复了工单','ticket.status_changed':'改了工单状态','ticket.published':'挂上公开页','ticket.unpublished':'撤下公开','ui.export':'导出'};
export function auditRows(events){return events.length?tableFrame(['时间','谁','动作','对象','结果','明细'],`${events.map(e=>`<tr role="row"><td role="cell"><span class="cell-label" aria-hidden="true">${'时间'}</span><div class="cell-value">${date(e.created_at)}</div></td><td role="cell"><span class="cell-label" aria-hidden="true">${'谁'}</span><div class="cell-value">${esc(({system:'市政厅机器',admin:'市政厅',player:'市民',hotel_owner:'酒店老板',anonymous:'路人',applicant:'申请人'})[e.actor_type]||e.actor_type)} #${e.actor_id||'—'} · ${esc(e.actor_name)}</div></td><td role="cell"><span class="cell-label" aria-hidden="true">${'动作'}</span><div class="cell-value">${esc(actionNames[e.action]||e.action)}</div></td><td role="cell"><span class="cell-label" aria-hidden="true">${'对象'}</span><div class="cell-value">${esc(({city_places:'地点与施工',sessions:'登录会话',tickets:'工单',ticket_events:'办理记录',ticket_rewards:'办结奖励',players:'市民账号',admins:'市政厅账号',hotel_owners:'酒店老板账号',hotels:'酒店',hotel_rooms:'房型',bookings:'预订',notification_log:'通知',media_uploads:'附件',direct_messages:'私信'})[e.resource_type]||e.resource_type)} #${esc(e.resource_id||'—')}</div></td><td role="cell"><span class="cell-label" aria-hidden="true">${'结果'}</span><div class="cell-value">${e.http_status||'—'}</div></td><td role="cell" class="wrap"><span class="cell-label" aria-hidden="true">${'明细'}</span><div class="cell-value">${esc(e.details||'')}</div></td></tr>`).join('')}`):`<div class="empty">${'这页还空着。翻页面、登录不算动过手。'}</div>`;}
export async function viewAudit(resourceType,resourceId){const dialog=modal('经手记录','<div class="wide" id="record-audit"></div>',{wide:true});await region($('#record-audit',dialog),()=>api('/api/admin/audit?resource_type='+encodeURIComponent(resourceType)+'&resource_id='+encodeURIComponent(resourceId)),(d,el)=>el.innerHTML=auditRows(d.events));}
export async function renderAudit(el){let snapshot=null,cursor=null;el.innerHTML=`<h2>${'谁动过手'}</h2><p class="muted">${'只记真动过手的操作和导出，翻页面、登录不算。密码、令牌和附件原文一律不进来。'}</p><div class="toolbar">${field('from','从哪天','date','',{required:false})}${field('to','到哪天','date','',{required:false})}${field('actor_type','身份','select','',{required:false,options:[['','全部'],['player','市民'],['admin','市政厅'],['hotel_owner','酒店老板'],['system','机器 / 灯灯']]})}${field('actor_id','账号编号','number','',{required:false,min:1})}<button id="audit-refresh">${'查'}</button><button id="audit-export">${'把筛选结果全导出来'}</button></div><div id="audit-rows"></div><button id="audit-next" hidden>${'再往后'}</button>`;
 const query=()=>{const p=new URLSearchParams();$$('[name]',el).forEach(e=>{if(e.value)p.set(e.name,e.value);});return p;};
 const load=()=>region($('#audit-rows',el),()=>{const q=query();if(snapshot!==null)q.set('snapshot',snapshot);if(cursor)q.set('cursor',cursor);return api('/api/admin/audit?'+q);},(d,box)=>{snapshot=d.snapshot;cursor=d.next_cursor;box.innerHTML=auditRows(d.events);$('#audit-next',el).hidden=!cursor;});
 $('#audit-refresh',el).onclick=()=>{snapshot=null;cursor=null;load();};$('#audit-next',el).onclick=load;
 $('#audit-export',el).onclick=e=>action(e.currentTarget,async()=>{const result=[];let next=null,cap=null;do{const q=query();q.set('limit','1000');if(cap!==null)q.set('snapshot',cap);if(next)q.set('cursor',next);const d=await api('/api/admin/audit?'+q);result.push(...d.events);cap=d.snapshot;next=d.next_cursor;}while(next);await csv('light-city-operation-audit.csv',result);});await load();
}
