import {$,$$,api,post,patch,region,tr,esc,text,date,empty,title,field,modal,action,toast,state} from './core.js';
import {feedbackMarkup,bindFeedback} from './reply-feedback.js';
import {createTicket,viewCitizenTicket} from './ticket-form.js';
function links(raw){try{const a=JSON.parse(raw||'[]');return Array.isArray(a)?a.filter(s=>Number.isSafeInteger(s.id)).map(s=>`<a href="${s.kind==='hotel'?'/hotel.html':'/knowledge.html?id='+s.id}">依据：${esc(s.title)}</a>`).join('<br>'):'';}catch{return '';}}
export async function renderChat(el){let peer='',epoch=0,timer=null;
 el.innerHTML=title('市民私信','Messages')+`<div class="toolbar"><button id="new-message" class="primary">＋ 写私信</button><button id="ai-message">🤖 联系灯灯</button><a class="button" href="/knowledge.html">查阅知识库</a></div><div class="split"><aside class="panel" id="conversations"></aside><section class="panel" id="thread">${empty('选择会话或写一封新私信')}</section></div>`;
 async function list(){await region($('#conversations',el),()=>api('/api/social?action=dm-list'),(d,box)=>{box.innerHTML=d.conversations.map((c,i)=>`<button class="conversation ${c.peer.username===peer?'selected':''}" data-conversation="${i}"><b>${esc(c.peer.username)}</b>${c.unread?` <span class="badge">${c.unread}</span>`:''}<small>${esc(c.last_content)}</small></button>`).join('')||empty();$$('[data-conversation]',box).forEach(b=>b.onclick=()=>open(d.conversations[Number(b.dataset.conversation)].peer.username));});}
 async function open(username){clearTimeout(timer);peer=username;const version=++epoch;await region($('#thread',el),()=>api('/api/social?action=dm-thread&peer='+encodeURIComponent(username)),async(d,box)=>{if(version!==epoch)return;box.innerHTML=`<div class="row-head"><h2>${esc(d.peer.username)}</h2><a href="/profile.html?u=${encodeURIComponent(d.peer.username)}">主页 ↗</a></div><div class="messages" aria-label="消息记录"></div>${username==='灯灯客服'?'<section class="chat-assistance" aria-label="回复反馈与人工客服"><div id="latest-reply-feedback"></div><div id="support-status"></div></section>':''}<form id="send-form">${field('content','消息内容','textarea')}<div class="actions"><button class="primary">发送 ↗</button></div></form><p role="status" id="chat-refresh-state"></p>`;
 let lastId=-1,chatRevision=-1,feedbackId=null;
 function placeSupportActions(){const controls=$('#support-actions',box),target=$('#latest-reply-feedback .reply-feedback .actions',box);if(controls&&target)target.append(controls);}
 function updateFeedback(messages){if(username!=='灯灯客服')return;const latest=messages.filter(m=>m.to_player_id===state.session.player.id).at(-1),target=$('#latest-reply-feedback',box);if(!latest||latest.id===feedbackId)return;if(target.contains(document.activeElement)&&document.activeElement.matches('textarea,select'))return;const controls=$('#support-actions',box);if(controls)$('#support-status',box).append(controls);feedbackId=latest.id;target.innerHTML='<p class="reply-context">评价这条回复：'+esc(latest.content.slice(0,70))+'</p>'+feedbackMarkup('dm',latest.id,latest.helpful);bindFeedback(target);placeSupportActions();}
 function drawMessages(messages,force=false){updateFeedback(messages);const last=messages.at(-1)?.id||0;if(!force&&last===lastId)return false;const target=$('.messages',box);if(!force&&target.contains(document.activeElement)&&document.activeElement.matches('textarea,select'))return false;lastId=last;const nearBottom=target.scrollHeight-target.scrollTop-target.clientHeight<80;target.innerHTML=messages.map(m=>`<div class="bubble ${m.from_player_id===state.session.player.id?'mine':''}"><p>${text(m.content)}</p>${links(m.knowledge_sources)}<small>${m.replied_by_admin_id?esc('人工客服 #'+m.replied_by_admin_id+' · '+(m.reply_author_name||''))+' · ':''}${date(m.created_at)}</small>${username==='灯灯客服'&&m.to_player_id===state.session.player.id&&m.id!==feedbackId?feedbackMarkup('dm',m.id,m.helpful):''}</div>`).join('')||empty();bindFeedback(target);if(force||nearBottom)target.scrollTop=target.scrollHeight;return true;}
 async function drawSupport(force=false){const result=await api('/api/support');if(version!==epoch||!box.isConnected)return;const chat=result.chat,revision=chat?.revision||0;if(!force&&revision===chatRevision)return;chatRevision=revision;const waiting=chat?.status==='queued',active=chat?.status==='active',bar=$('#support-status',box);$('#support-actions',box)?.remove();bar.innerHTML=`<p>${waiting?'已转人工，正在等待客服接入。继续在这个聊天补充说明即可。':active?'人工客服已接入，灯灯自动回复已暂停。':chat?.auto_handoff===false?'已结束人工等待。可以继续与灯灯交流，需要时手动转人工。':'灯灯会根据资料组织答复；无法可靠回答时，会在当前聊天自动转人工。'}</p><div class="actions" id="support-actions">${waiting||active?`<button type="button" id="end-support">${waiting?'结束等待':'结束人工会话'}</button>`:'<button type="button" id="handoff">转人工</button>'}<button type="button" id="support-refresh">刷新回复</button>${chat?.linked_ticket_id?'<button type="button" id="linked-ticket">查看已提交工单</button>':chat?.needs_ticket?'<button type="button" class="primary" id="suggested-ticket">提交工单</button>':''}</div>${chat?.needs_ticket&&!chat.linked_ticket_id?'<p>人工客服建议通过工单继续处理。点击后可核对问题说明，再确认提交。</p>':''}`;
 const refresh=async()=>{const r=await api('/api/social?action=dm-thread&peer='+encodeURIComponent(username));drawMessages(r.messages);await drawSupport(true);await patch('/api/social?action=dm-read&peer='+encodeURIComponent(username));await list();};$('#support-refresh',bar).onclick=e=>action(e.currentTarget,refresh);
 if($('#handoff',bar))$('#handoff',bar).onclick=e=>action(e.currentTarget,async()=>{await post('/api/support',{});await refresh();});
 if($('#end-support',bar))$('#end-support',bar).onclick=e=>action(e.currentTarget,async()=>{await post('/api/support',{action:'cancel',revision:chat.revision});await refresh();});
 if($('#linked-ticket',bar))$('#linked-ticket',bar).onclick=e=>action(e.currentTarget,()=>viewCitizenTicket(chat.linked_ticket_id));
 if($('#suggested-ticket',bar))$('#suggested-ticket',bar).onclick=e=>action(e.currentTarget,()=>createTicket({kind:'service',initial:{title:'人工客服建议跟进的问题',body:chat.ticket_summary||''},onCreated:async t=>{await post('/api/support',{action:'link-ticket',ticket_id:t.id});await drawSupport(true);}}));
 placeSupportActions();
 }
 drawMessages(d.messages,true);if(username==='灯灯客服')await drawSupport(true);$('#send-form',box).onsubmit=e=>{e.preventDefault();const form=e.currentTarget;action($('button',form),async()=>{const result=await post('/api/social?action=dm-send',{to_username:username,content:$('[name=content]',form).value});if(version===epoch){$('[name=content]',form).value='';const r=await api('/api/social?action=dm-thread&peer='+encodeURIComponent(username));drawMessages(r.messages,true);if(username==='灯灯客服')await drawSupport(true);await patch('/api/social?action=dm-read&peer='+encodeURIComponent(username));await list();if(result.support_error)toast('消息已保存，但自动转人工暂未成功，请点击“转人工”重试',true);}});};
 await patch('/api/social?action=dm-read&peer='+encodeURIComponent(username));await list();
 async function poll(){timer=setTimeout(async()=>{if(!el.isConnected||version!==epoch)return;try{if(document.visibilityState!=='hidden'){const r=await api('/api/social?action=dm-thread&peer='+encodeURIComponent(username));if(version!==epoch)return;if(drawMessages(r.messages)){await patch('/api/social?action=dm-read&peer='+encodeURIComponent(username));await list();}if(username==='灯灯客服')await drawSupport();$('#chat-refresh-state',box).textContent='';}}catch{$('#chat-refresh-state',box).textContent='暂时无法刷新，可点击刷新回复重试。';}if(el.isConnected&&version===epoch)poll();},5000);}poll();
 });}
 $('#new-message',el).onclick=()=>modal('新私信',field('username','收件人游戏 ID'),{label:'打开会话',submit:async v=>{await open(v.username);}});$('#ai-message',el).onclick=e=>action(e.currentTarget,async()=>{const d=await api('/api/ai-bot');await open(d.username);});await list();const to=new URLSearchParams(location.search).get('to');if(to)await open(to);
}
