import {$,$$,api,post,esc,text,date,empty,title,field,modal,action,toast} from './core.js';
import {viewAudit} from './audit-ui.js';
const categories=[['facility','公共设施'],['hotel','酒店'],['rail','铁路 / 车站'],['road','道路'],['park','绿化']];
const states=[['open','正常开放'],['planned','计划施工'],['construction','施工中'],['closed','暂时关闭']];
const label=(list,key)=>list.find(r=>r[0]===key)?.[1]||key;
export async function render(el){return mapView(el,false);}
export async function renderMapAdmin(el){return mapView(el,true);}
async function mapView(el,manage){
 el.innerHTML=(manage?'<div class="section-head"><h2>地图与施工管理</h2></div>':title('城市地图与施工','City map'))+`<section class="pane pane-pad-lg"><p>${manage?'由 SUPER 维护真实地点。先保存草稿，确认坐标与说明后发布；施工和恢复信息直接在地点中更新。':'主世界坐标示意图由超管维护，并非实时游戏地形。施工状态与预计恢复日期以地点说明为准。'}</p><div class="toolbar-modern">${field('q','搜索地点','search','',{required:false})}${field('category','分类','select','',{required:false,options:[['','全部分类'],...categories]})}${field('work','施工状态','select','',{required:false,options:[['','全部状态'],...states]})}<div class="toolbar-tools"><button id="map-refresh">刷新</button>${manage?'<button id="map-add" class="primary">＋ 添加地点</button>':''}</div></div></section><div class="city-map-section"><section class="pane pane-pad-sm"><div id="map-plot" class="city-map" aria-label="地点坐标示意图"></div><p class="muted" style="margin:8px 0 0">上方为北（Z 减小），右方为东（X 增大）。图上编号对应下方地点，点击编号查看。</p></section><div class="city-map-aside" id="map-list"></div></div>`;
 let places=[];
 function draw(){const q=$('[name=q]',el).value.trim().toLowerCase(),category=$('[name=category]',el).value,work=$('[name=work]',el).value;const rows=places.filter(p=>p.dimension==='overworld'&&(!category||p.category===category)&&(!work||p.construction_status===work)&&(!q||(p.name+' '+p.description+' '+p.construction_note).toLowerCase().includes(q)));
 const xs=rows.map(p=>p.x),zs=rows.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);
 $('#map-plot',el).innerHTML=rows.length?rows.map((p,i)=>`<button type="button" class="map-pin ${p.construction_status==='open'?'':'map-work'}" style="left:${10+80*(maxX===minX?.5:(p.x-minX)/(maxX-minX))}%;top:${10+80*(maxZ===minZ?.5:(p.z-minZ)/(maxZ-minZ))}%" data-pin="${p.id}" aria-label="${esc(p.name)} · ${label(states,p.construction_status)}">${i+1}</button>`).join(''):empty('暂无符合条件的地点');
 $('#map-list',el).innerHTML=rows.map((p,i)=>`<article class="panel" id="place-${p.id}" tabindex="-1"><div class="row-head"><h2>${i+1}. ${esc(p.name)}</h2><span class="badge">${label(states,p.construction_status)}${manage?(p.published?' · 已发布':' · 草稿'):''}</span></div><p>${label(categories,p.category)} · 主世界 · X ${p.x} / Z ${p.z}</p><p>${text(p.description)}</p>${p.construction_status!=='open'||p.construction_note?`<div class="notice"><b>施工与通行信息</b><p>${text(p.construction_note||'尚未填写详细说明')}</p>${p.expected_end?`<p>预计恢复：${esc(p.expected_end)}（预计时间，可能调整）</p>`:''}</div>`:''}<small>更新于 ${date(p.updated_at)}</small><div class="actions"><button data-copy="${p.id}">复制坐标</button>${manage?`<button data-edit="${p.id}">编辑 / 发布 / 更新施工</button><button data-audit="${p.id}">操作留痕</button>`:''}</div></article>`).join('')||empty('暂无地点；真实资料由超管添加后展示');
 $$('[data-pin]',el).forEach(b=>b.onclick=()=>{const card=$('#place-'+b.dataset.pin,el);card.scrollIntoView({block:'start',behavior:'auto'});card.focus({preventScroll:true});});$$('[data-copy]',el).forEach(b=>b.onclick=e=>action(e.currentTarget,async()=>{const p=places.find(p=>p.id===+b.dataset.copy);try{await navigator.clipboard.writeText(`${p.name} · 主世界 · X ${p.x} / Z ${p.z}`);toast('坐标已复制');}catch{toast('无法自动复制，请复制地点卡片上的坐标',true);}}));$$('[data-edit]',el).forEach(b=>b.onclick=()=>edit(places.find(p=>p.id===+b.dataset.edit)));$$('[data-audit]',el).forEach(b=>b.onclick=()=>viewAudit('city_places',b.dataset.audit).catch(e=>toast(e.message,true)));
 }
 async function load(){try{places=(await api('/api/city-map'+(manage?'?manage=1':''))).places;draw();}catch(e){$('#map-list',el).innerHTML=empty(e.message);toast(e.message,true);}}
 function edit(p={}){modal(p.id?'编辑地点与施工':'添加地点',field('name','地点名称','text',p.name||'',{maxlength:80})+field('category','分类','select',p.category||'facility',{options:categories})+field('x','X 坐标','number',p.x??0)+field('z','Z 坐标','number',p.z??0)+field('description','地点说明','textarea',p.description||'',{required:false,maxlength:2000})+field('construction_status','施工 / 开放状态','select',p.construction_status||'open',{options:states})+field('construction_note','施工与绕行说明','textarea',p.construction_note||'',{required:false,maxlength:1500})+field('expected_end','预计恢复日期（可留空）','date',p.expected_end||'',{required:false})+field('published','展示状态','select',p.published??0,{options:[[0,'草稿 / 不公开'],[1,'发布到地图']]}),{submit:async values=>{await post('/api/city-map',{...values,dimension:'overworld',...(p.id?{id:p.id,revision:p.revision}:{})});await load();}});}
 $$('input,select',el).forEach(x=>x.addEventListener('input',draw));$('#map-refresh',el).onclick=load;if(manage)$('#map-add',el).onclick=()=>edit();await load();const selected=places.find(p=>location.hash==='#place-'+p.id);if(selected){draw();$('#place-'+selected.id,el)?.scrollIntoView({block:'start'});}
}
