import {$,api,patch,esc,tr,modal,field,action,toast,state} from './core.js';
export async function renderDispatchPolicy(el){
 const data=await api('/api/admin/dispatch-settings');const {config,preferred}=data;
 const name=a=>a?`#${a.id} · ${a.username}`:tr('未唯一匹配，请超管指定账号','No unique match; select an account');
 el.innerHTML=`<div class="panel"><div class="row-head"><h3>${tr('自动派单','Automatic assignment')} · ${tr(config.enabled?'已启用':'已暂停',config.enabled?'Enabled':'Paused')}</h3>${state.session?.user?.role==='super'?`<button id="dispatch-config">${tr('调整分工 / 开关','Edit policy / toggle')}</button>`:''}</div><p>${tr('紧急优先','Urgent')}: <b>${esc(name(preferred.urgent))}</b> · ${tr('复杂优先','Complex')}: <b>${esc(name(preferred.complex))}</b></p><p class="muted">${tr('新工单提交后自动派出；紧急且复杂时先按紧急处理。人工改派不会被覆盖。','New tickets are assigned automatically; urgency takes precedence over complexity. Manual assignment is preserved.')}</p><p>${tr('每人最多在办','Active limit per administrator')}: ${config.max_active} · ${tr(data.ai_configured?'AI 分类与历史经验辅助':'未配置 AI：分工规则与历史统计自动派单',data.ai_configured?'AI classification and historical experience':'AI not configured: policy and history-based routing')}</p><details><summary>${tr('查看学习依据','Learning evidence')}</summary><p>${tr('近 180 天同类事项由承办人亲自办结的记录，综合完成数、耗时、重开比例与当前工作量；少于 3 个样本不推断专长。统计在每次派单时更新，不会修改模型或权限。','Uses comparable work completed by its assigned handler in the last 180 days, duration, reopen rate and workload; at least 3 samples are required. Recomputed for each assignment; no model training or permission changes.')}</p>${data.experience.length?`<ul>${data.experience.map(e=>`<li>#${e.admin_id} · ${tr('办结','Completed')} ${e.completed} · ${tr('平均小时','Average hours')} ${Number(e.average_hours||0).toFixed(1)} · ${tr('曾重开','Reopened')} ${e.reopened}</li>`).join('')}</ul>`:`<p>${tr('尚无足够历史，先按分工与工作量派单。','Insufficient history; using policy and workload.')}</p>`}</details></div>`;
 $('#dispatch-config',el)?.addEventListener('click',e=>action(e.currentTarget,async()=>{
 const options=[['',tr('按指定名字自动匹配','Match designated name automatically')],...data.admins.map(a=>[a.id,`#${a.id} · ${a.username}${a.player_username?' / '+a.player_username:''}`])];
 modal(tr('自动派单设置','Automatic assignment settings'),field('enabled',tr('启用新工单自动派单','Automatically assign new tickets'),'checkbox',config.enabled)+field('urgent_admin_id',tr('紧急事项优先（wzc）','Urgent preference (wzc)'),'select',config.urgent_admin_id||'',{required:false,options})+field('complex_admin_id',tr('复杂事项优先（漫画家）','Complex preference (漫画家)'),'select',config.complex_admin_id||'',{required:false,options})+field('max_active',tr('每人最多在办工单','Maximum active tickets per administrator'),'number',config.max_active,{min:1,max:100}),{submit:async values=>{await patch('/api/admin/dispatch-settings',values);toast(tr('自动派单规则已更新','Assignment policy updated'));await renderDispatchPolicy(el);}});
 }));
}
