import {$,$$,api,post,patch,tr,esc,text,action,date} from './core.js';
const labels={choice:'单选题',multi:'多选题',short:'简答题'};
export async function renderSurvey(el){
 let session=null,timer=null,queue=Promise.resolve(),dirty=false;
 el.innerHTML='<h3>驾照模拟考试</h3><p class="notice">选择等级后即时生成本次问卷：2 道单选、1 道多选、2 道简答，共 100 分。作答时不提供参考资料或答案，全部完成后统一交卷。此成绩不自动改变正式驾照审批。</p><div class="actions">'+['B','A','S'].map(g=>`<button data-exam-grade="${g}">${g} 级 · 开始答卷</button>`).join('')+'</div><p role="status" id="exam-status"></p><div id="exam-paper"></div><h3>我的答卷记录</h3><div id="exam-history"></div>';
 const note=message=>{if(el.isConnected)$('#exam-status',el).textContent=message;};
 function collect(){const result={};if(!session?.questions)return result;for(const q of session.questions){result[q.id]=q.type==='short'?$(`[data-short="${q.id}"]`,el)?.value||'':$$(`[name="q-${q.id}"]:checked`,el).map(x=>x.value);}return result;}
 function progress(){const a=collect(),n=Object.values(a).filter(v=>typeof v==='string'?v.trim():v.length).length;$('#exam-progress',el).textContent=`已作答 ${n} / ${session.questions.length} 题`;$('progress',el).value=n;}
 function save(){const current=session;if(!current||current.status!=='in_progress')return queue;const answers=collect();queue=queue.catch(()=>{}).then(async()=>{const r=await patch('/api/exam-sessions',{session_id:current.id,revision:current.revision,answers});current.revision=r.revision;current.answers=answers;if(session===current){dirty=JSON.stringify(collect())!==JSON.stringify(answers);note(dirty?'有新的修改，等待保存':'进度已保存，可以稍后继续');}});return queue;}
 function watch(id){setTimeout(async()=>{if(!el.isConnected||session?.id!==id||!['generating','grading'].includes(session.status))return;try{const d=await api('/api/exam-sessions?id='+encodeURIComponent(id));draw(d.session);if(['completed','needs_review'].includes(d.session.status))await history();}catch(e){note(e.message);}},2500);}
 function draw(s){clearTimeout(timer);session=s;dirty=false;note(!s?'请选择等级开始':s.status==='in_progress'?'本次试卷可继续作答':s.status==='generating'?'正在生成试卷…':s.status==='grading'?'答卷已锁定，正在批改…':['completed','needs_review'].includes(s.status)?'答卷已提交，不能再修改':'本次试卷未完成');const box=$('#exam-paper',el);$$('[data-exam-grade]',el).forEach(b=>b.disabled=!!s&&['generating','in_progress','grading'].includes(s.status));
  if(!s){box.innerHTML='';return;}if(s.status==='generating'||s.status==='grading'){box.innerHTML=`<div class="panel"><h3>${s.status==='generating'?'正在生成本次试卷':'答卷已锁定，正在批改'}</h3><p>${s.status==='generating'?'请稍候。刷新后也会继续这份试卷。':'选择题由系统判分，简答题正在逐项评阅。'}</p>${s.status==='grading'?'<button id="recover-exam">检查批改进度</button>':''}</div>`;if(s.status==='grading')$('#recover-exam',el).onclick=e=>action(e.currentTarget,async()=>{const d=await post('/api/exam-sessions',{action:'recover',session_id:s.id});draw(d.session);});watch(s.id);return;}
  if(s.status==='failed'||s.status==='abandoned'){box.innerHTML='<p class="notice">本次试卷未完成，可以重新选择等级开始。</p>';return;}
  const editable=s.status==='in_progress';box.innerHTML=`<section class="panel"><div class="row-head"><h3>${esc(s.grade)} 级 · 本次答卷</h3><span>${editable?'作答中':s.status==='needs_review'?'简答待复核':'已完成'}</span></div>${editable?'<p id="exam-progress" aria-live="polite"></p><progress max="5" value="0" aria-label="答题进度"></progress>':`<p class="notice">${s.score===null?`已确认 ${s.known_score} 分，${s.pending_count} 道简答待复核，总分尚未确定。`:`本次得分 ${s.score} / 100`}</p>`}<form id="exam-form">${s.questions.map((q,i)=>`<fieldset class="survey-question"><legend>${i+1}. ${labels[q.type]} · ${q.max_score} 分</legend><p>${text(q.prompt)}</p>${q.type==='short'?`<label>你的回答<textarea data-short="${q.id}" maxlength="2000" rows="5" ${editable?'':'disabled'}>${esc(s.answers[q.id]||'')}</textarea></label>`:q.options.map(o=>`<label class="survey-option"><input type="${q.type==='multi'?'checkbox':'radio'}" name="q-${q.id}" value="${o.id}" ${(s.answers[q.id]||[]).includes(o.id)?'checked':''} ${editable?'':'disabled'}><span>${esc(o.text)}</span></label>`).join('')}${!editable?(()=>{const r=s.results?.find(x=>x.question_id===q.id);return r?`<p class="notice">${r.score===null?'待复核':r.score+' / 20 分'} · ${esc(r.feedback)}${r.grader?.type==='admin'?' · 管理员 #'+r.grader.id+' '+esc(r.grader.name):r.grader?.type==='ai'?' · AI 批改':''}</p>`:'';})():''}</fieldset>`).join('')}${editable?'<div class="actions survey-actions"><button type="button" id="exam-save">保存进度</button><button type="submit" class="primary">统一交卷</button><button type="button" id="exam-abandon">放弃本次试卷</button></div><p class="muted">输入后会自动保存。离开前请确认已显示“进度已保存”；未作答的题目按 0 分处理。交卷后不能修改。</p>':''}</form></section>`;
  if(!editable)return;progress();$('#exam-form',el).oninput=()=>{dirty=true;progress();note('正在编辑，等待保存…');clearTimeout(timer);timer=setTimeout(()=>{if(el.isConnected)save().catch(e=>note('保存失败：'+e.message));},1200);};$('#exam-save',el).onclick=e=>action(e.currentTarget,async()=>{clearTimeout(timer);await save();});
  $('#exam-form',el).onsubmit=e=>{e.preventDefault();action($('[type=submit]',e.currentTarget),async()=>{clearTimeout(timer);const controls=$$('input,textarea,button',e.currentTarget);controls.forEach(x=>x.disabled=true);try{await save();const d=await post('/api/exam-sessions',{action:'submit',session_id:s.id,revision:s.revision,answers:collect()});draw(d.session);await history();}finally{if(session===s&&session.status==='in_progress')controls.forEach(x=>x.disabled=false);}});};
  $('#exam-abandon',el).onclick=e=>action(e.currentTarget,async()=>{clearTimeout(timer);await queue.catch(()=>{});await post('/api/exam-sessions',{action:'abandon',session_id:s.id});draw(null);note('已放弃本次试卷，可以重新选择等级');});
 }
 async function history(){const d=await api('/api/exam-sessions');if(!el.isConnected)return;$('#exam-history',el).innerHTML=d.history.map(h=>`<div class="row row-head"><span>${esc(h.grade)} 级 · ${date(h.submitted_at)} · ${h.score===null?'待复核':h.score+' 分'}</span><button data-exam-history="${h.id}">查看答卷</button></div>`).join('')||'<p class="muted">还没有已交答卷。</p>';$$('[data-exam-history]',el).forEach(b=>b.onclick=e=>action(e.currentTarget,async()=>{if(dirty){await save();}const r=await api('/api/exam-sessions?id='+encodeURIComponent(b.dataset.examHistory));draw(r.session);}));return d;}
 $$('[data-exam-grade]',el).forEach(b=>b.onclick=e=>action(e.currentTarget,async()=>{note('正在为你生成试卷…');const d=await post('/api/exam-sessions',{grade:b.dataset.examGrade});draw(d.session);note(d.resumed?'已恢复尚未完成的试卷':'本次试卷已生成');}));const d=await history();if(d?.active)draw(d.active);
}
