import {$,$$,api,post,patch,tr,esc,text,date,status,title,field,modal,region,action,toast,state,login,session,csv} from './core.js';
import {attachmentPicker} from './attachments.js';
export async function render(el){
 if(!state.session?.hotel_owner){el.innerHTML=title('酒店自助管理','Hotel self service')+`<div class="panel"><h2>${tr('酒店老板专属平台','Hotel owner platform')}</h2><p>${tr('经营账户由超管创建，并分配可管理的酒店。已关联经营账户的玩家也可直接进入。','Accounts and hotels are assigned by a super administrator. Linked citizens can also enter directly.')}</p><button id="owner-login" class="primary">${tr('酒店老板登录','Owner sign in')}</button></div>`;$('#owner-login',el).onclick=async()=>{await login(false,'hotel_owner');await session();if(state.session?.hotel_owner)render(el);};return;}
 el.innerHTML=title('我的酒店管理','My hotel management')+`<div class="tabs-segment" role="tablist" aria-label="酒店管理"><button type="button" role="tab" data-owner-tab="hotels" aria-selected="true">${tr('酒店资料','Hotels')}</button><button type="button" role="tab" data-owner-tab="rooms">${tr('房型与价格','Rooms & prices')}</button><button type="button" role="tab" data-owner-tab="bookings">${tr('预订处理','Bookings')}</button></div><div id="owner-body" class="card-list" style="margin-top:24px"></div>`;let tab='hotels',data;
 const refresh=()=>region($('#owner-body',el),()=>api('/api/hotel-owner'),(d,box)=>{data=d;draw(box);});
 function draw(box){const list=data[tab];box.innerHTML=`<div class="section-head"><h2>${tr(tab==='hotels'?'酒店资料':tab==='rooms'?'房型与价格':'预订处理',tab)}</h2><div class="actions compact"><button id="owner-refresh">${tr('刷新','Refresh')}</button>${tab==='rooms'&&data.hotels.length?`<button id="owner-new">＋ ${tr('新建房型','New room')}</button>`:''}</div></div>`+(list.length?`<div class="feature-grid">${list.map(r=>`<article class="feature-card"><h3>${esc(r.name||r.room_name||'#'+r.id)}</h3>${tab==='bookings'?`<p>${esc(r.player_username||r.name)} · ${esc(r.contact)}</p><p>${esc(r.in_date)} → ${esc(r.out_date)}</p>${status(r.status)}`:`<p>${text(r.description||'')}</p><p>${tab==='rooms'?'💎 '+r.price_per_night+' / '+tr('晚','night') :esc(r.address)}</p>${status(r.is_active?'active':'pending')}`}<div class="feature-foot"><button data-edit="${r.id}">${tr(tab==='bookings'?'处理预订':'编辑',tab==='bookings'?'Review':'Edit')}</button><button data-history="${r.id}">${tr('操作记录','History')}</button></div></article>`).join('')}</div>`:`<div class="empty-modern"><span class="empty-icon" aria-hidden="true">🏨</span><p>${tr(data.hotels.length?'暂无记录':'还没有分配给你的酒店，请联系超管。',data.hotels.length?'No records':'No hotel assigned. Contact a super administrator.')}</p></div>`);
 $('#owner-refresh',box).onclick=refresh;$('#owner-new',box)?.addEventListener('click',()=>edit({}));$$('[data-history]',box).forEach(b=>b.onclick=()=>action(b,async()=>{const d=await api(`/api/hotel-owner?history=1&entity=${tab}&id=${b.dataset.history}`);modal(tr('操作记录','Operation history'),`<div class="wide">${d.events.map(e=>`<div class="row"><b>${esc(e.actor_name)} #${e.actor_id}</b><p>${esc(tr(({post:'创建',patch:'修改','db.insert':'保存记录','db.update':'更新记录','db.delete':'删除记录'})[e.action]||e.action,e.action))} · ${date(e.created_at)}</p></div>`).join('')||tr('暂无记录','No records')}</div>`);}));$$('[data-edit]',box).forEach(b=>b.onclick=()=>edit(list.find(r=>r.id===+b.dataset.edit)));
 }
 function edit(record){if(tab==='bookings'){modal(tr('处理酒店预订','Review booking'),`<div class="notice wide">${esc(record.room_name)} · ${esc(record.in_date)} → ${esc(record.out_date)}</div>`+field('status',tr('预订状态','Status'),'select',record.status,{options:[['pending',tr('待确认','Pending')],['confirmed',tr('已确认','Confirmed')],['completed',tr('已完成','Completed')],['cancelled',tr('已取消','Cancelled')]]}),{submit:async d=>{await patch('/api/hotel-owner?entity=bookings&id='+record.id,d);await refresh();}});return;}
 const room=tab==='rooms';let picker;const content=(room?field('hotel_id',tr('所属酒店','Hotel'),'select',record.hotel_id||data.hotels[0].id,{options:data.hotels.map(h=>[h.id,h.name])}):'')+field('name',tr('名称','Name'),'text',record.name||'')+(room?field('capacity',tr('入住人数','Capacity'),'number',record.capacity||2,{min:1,max:6})+field('beds',tr('床型','Beds'),'text',record.beds||'',{required:false})+field('price_per_night',tr('每晚价格','Nightly price'),'number',record.price_per_night||0,{min:0})+field('breakfast_included',tr('含早餐','Breakfast included'),'checkbox',record.breakfast_included??1):field('address',tr('地址','Address'),'text',record.address||'',{required:false}))+field('description',tr('介绍','Description'),'textarea',record.description||'',{required:false})+field('image_url',tr('图片 URL（或下方上传）','Image URL (or upload below)'),'text',record.image_url||'',{required:false})+field('is_active',tr('开放','Open'),'checkbox',record.is_active??1);
 const dialog=modal(tr('编辑酒店信息','Edit hotel information'),content,{wide:true,submit:async d=>{const images=picker.files();if(images.length)d.image_url=images[0].url;await (record.id?patch(`/api/hotel-owner?entity=${tab}&id=${record.id}`,d):post('/api/hotel-owner?entity=rooms',d));picker.commit();await refresh();toast(tr('已保存','Saved'));}});picker=attachmentPicker(dialog,{purpose:'public-image',max:1});}
 $$('[data-owner-tab]',el).forEach(b=>b.onclick=()=>{tab=b.dataset.ownerTab;$$('[data-owner-tab]',el).forEach(x=>x.setAttribute('aria-selected',x===b));if(data)draw($('#owner-body',el));});await refresh();
}
