import {feedbackMarkup,bindFeedback} from './reply-feedback.js';
import {$,$$,api,post,patch,field,modal,requirePlayer,tr,toast,esc,text,ticketBody,status,action,date} from './core.js';
import {attachmentPicker,renderAttachments} from './attachments.js';
import {MAX_ATTACHMENTS} from '../../shared/uploads.js';
export const replyAuthor=t=>t.replied_by?`${tr('管理员','Admin')} #${t.replied_by} · ${t.reply_author_name||tr('历史账号','Historical account')}`:tr('历史回复，未记录署名','Historical reply; author not recorded');
export function ticketTimeline(events=[]){const labels={triage_resumed:['恢复自动分级','Automatic triage resumed'],triaged:['内部优先级评估','Internal triage'],priority_changed:['调整内部优先级','Priority changed'],reopened:['重新处理','Reopened'],player_question:['市民追问','Citizen question'],auto_replied:['灯灯自动基础回复','Automatic first reply'],human_requested:['请求转人工','Human support requested'],player_followup:['市民补充说明','Citizen follow-up'],dispatch_deferred:['自动派单暂缓','Automatic assignment deferred'],business_updated:['更新关联业务','Linked business updated'],created:['提交工单','Created'],assigned:['派单','Assigned'],replied:['回复工单','Replied'],status_changed:['更新状态','Status changed'],published:['公开处理','Published'],unpublished:['取消公开','Unpublished'],consent_changed:['修改公开授权','Consent changed'],attachments_added:['补充附件','Attachments added']};return `<section class="ticket-history"><h3>${tr('办理记录','Processing history')}</h3>${events.length?events.map(e=>{let d={};try{d=JSON.parse(e.details);}catch{}return `<div class="row"><div class="row-head"><b>${esc((e.actor_type==='system'?tr('系统','System'):e.actor_type==='admin'?tr('管理员','Admin'):e.actor_type==='hotel_owner'?tr('酒店老板','Hotel owner'):tr('玩家','Citizen'))+(e.actor_id?' #'+e.actor_id:'')+' · '+e.actor_name)}</b><small>${date(e.created_at)}</small></div><p>${esc(labels[e.action]?tr(...labels[e.action]):e.action)}${e.action==='assigned'?` → ${esc(d.to?'#'+d.to+' '+(d.name||''):tr('未派单','Unassigned'))}`:''}${e.action==='assigned'&&d.mode==='automatic'?` · ${esc(d.source==='ai'?tr('AI 自动派单','AI assignment'):tr('规则自动派单','Rule assignment'))}<br>${esc(d.reason||'')}`:''}${e.action==='dispatch_deferred'?` · ${esc(d.reason||'')}`:''}${e.action==='triaged'?` · ${esc(d.priority||'')} / ${esc(d.urgency||'')} / ${esc(d.complexity||'')}<br>${esc(d.reason||'')} · ${esc(d.source||'')}`:''}${e.action==='priority_changed'?` · ${esc(d.from||'')} → ${esc(d.to||'')}`:''}${e.action==='business_updated'?` · ${status(d.status)}`:''}${e.action==='status_changed'?` · ${status(d.to)}`:''}</p>${['replied','auto_replied','player_followup','player_question'].includes(e.action)?`<div>${text(d.reply)}</div>`:''}</div>`;}).join(''):`<p class="muted">${tr('历史工单尚无新增操作记录','No new processing events recorded yet')}</p>`}</section>`;}
export async function showAdminDirectory(){await requirePlayer();const d=await api('/api/directory?kind=admins');modal(tr('管理员编号名录','Administrator directory'),`<div class="wide"><p>${tr('投诉管理员时请选择对应编号，避免同名混淆。','Use the administrator ID when filing a complaint.')}</p>${d.admins.map(a=>`<div class="row"><b>#${a.id}</b> · ${esc(a.username)}</div>`).join('')}</div>`);}
export async function createTicket({kind='message',onCreated=()=>{},initial={}}={}){
 const player=await requirePlayer();const directory=await api('/api/directory?kind=admins');let picker,players=[];
 const dialog=modal(tr('留言与工单','Messages & tickets'),field('kind',tr('事项类型','Request type'),'select',kind,{options:[['message',tr('留言建议','Message / suggestion')],['service',tr('市民服务','Citizen service')],['bug',tr('反馈 Bug','Report a bug')],['report',tr('举报玩家','Report a player')],['admin_complaint',tr('投诉管理员','Complain about an administrator')]]})+
 field('target_player_name',tr('被举报玩家（可匹配或自填）','Reported player (match or enter a name)'),'text','',{required:false,maxlength:64})+'<datalist id="report-player-options"></datalist><input type="hidden" name="target_player_id">'+
 field('target_admin_id',tr('被投诉管理员编号','Administrator being reported'),'select','',{required:false,options:[['',tr('请选择管理员','Choose administrator')],...directory.admins.map(a=>[a.id,`#${a.id} · ${a.username}`])]})+
 field('title',tr('简要标题','Title'),'text',initial.title||'',{maxlength:90})+field('body',tr('详细说明','Description'),'textarea',initial.body||'',{maxlength:2000})+field('contact',tr('联系方式（仅处理人员可见）','Contact (private)'),'text',player.email||'',{required:false})+
 field('public_consent',tr('同意该工单公开处理（经审核后公开文字和答复，附件仍私密）','Allow public processing (reviewed text/replies only; attachments stay private)'),'checkbox',false)+
 `<p class="muted wide">${tr('请说明时间、地点、相关账号和复现步骤。未同意公开的工单只由你和有权限的处理人员查看。','Include time, location, accounts and reproduction steps. Without consent, only you and authorized staff can view this ticket.')}</p>`,{wide:true,label:tr('提交','Submit'),submit:async values=>{
  const result=await post('/api/tickets',{...values,attachment_ids:picker.ids()});picker.commit();toast(tr('工单已提交，可在“我的工单”查看办理进度','Submitted. Check My tickets for progress.'));try{await onCreated(result);}catch(e){toast(e.message,true);}
 }});
 const kindInput=$('[name=kind]',dialog),nameInput=$('[name=target_player_name]',dialog),adminInput=$('[name=target_admin_id]',dialog),idInput=$('[name=target_player_id]',dialog);nameInput.setAttribute('list','report-player-options');let timer;
 const setTargets=()=>{const reporting=kindInput.value==='report',complaint=kindInput.value==='admin_complaint';nameInput.closest('label').hidden=!reporting;nameInput.disabled=!reporting;nameInput.required=reporting;idInput.disabled=!reporting;adminInput.closest('label').hidden=!complaint;adminInput.disabled=!complaint;adminInput.required=complaint;};kindInput.onchange=setTargets;setTargets();
 nameInput.addEventListener('input',()=>{idInput.value=players.find(p=>p.username===nameInput.value.trim())?.id||'';clearTimeout(timer);timer=setTimeout(async()=>{try{const q=nameInput.value.trim();const d=await api('/api/directory?kind=players&q='+encodeURIComponent(q));if(!dialog.isConnected||nameInput.value.trim()!==q)return;players=d.players;$('#report-player-options',dialog).innerHTML=players.map(p=>`<option value="${esc(p.username)}">#${p.id}</option>`).join('');idInput.value=players.find(p=>p.username===q)?.id||'';}catch{}},200);});
 dialog.addEventListener('close',()=>clearTimeout(timer));picker=attachmentPicker(dialog);return dialog;
}
export async function viewCitizenTicket(id,{onChanged=()=>{}}={}){
 const data=await api('/api/tickets?my=1&id='+encodeURIComponent(id)),ticket=data.ticket;let picker;const remaining=MAX_ATTACHMENTS-(ticket.attachments||[]).length;
 const dialog=modal(ticket.title,`<div class="wide">${progressMarkup(ticket)}<div class="row-head">${status(ticket.status)}<span>${tr(ticket.public_visible?'已公开处理':ticket.public_consent?'已授权公开，待审核':'私密处理',ticket.public_visible?'Public':ticket.public_consent?'Consent given; awaiting review':'Private')}</span></div><div>${ticketBody(ticket.body)}</div>${ticket.target_admin_id?`<p>${tr('被投诉管理员','Reported administrator')} #${ticket.target_admin_id}</p>`:''}${ticket.target_player_name?`<p>${tr('被举报玩家','Reported player')}：${esc(ticket.target_player_name)} ${ticket.target_player_id?'#'+ticket.target_player_id:tr('（自填姓名）','(entered name)')}</p>`:''}${ticket.admin_reply?`<div class="notice"><b>${esc(replyAuthor(ticket))}</b><small> · ${date(ticket.replied_at)}</small><p>${text(ticket.admin_reply)}</p></div>`:''}${ticket.auto_reply?`<div class="notice"><b>${tr('灯灯 · 自动基础回复','DengDeng · Automatic first reply')}</b><p>${text(ticket.auto_reply)}</p></div>`:''}${renderAttachments(ticket.attachments)}${ticket.reward?`<p class="notice">${tr('承办奖励','Handler reward')}：10 💎 · ${tr(ticket.reward.paid?'已发放':'待绑定玩家后发放',ticket.reward.paid?'Paid':'Pending linked citizen')} · ${tr('管理员','Admin')} #${ticket.reward.admin_id}</p>`:''}<button type="button" id="consent-toggle">${tr(ticket.public_consent?'撤回公开授权':'同意公开处理',ticket.public_consent?'Withdraw public consent':'Allow public processing')}</button>${ticketTimeline(ticket.history)}<section class="ticket-followup"><h3>补充说明与追问</h3>${field('followup_kind','类型','select','followup',{options:[['followup','补充说明'],['question','追问处理情况']]})}${field('followup_content','补充内容','textarea','',{required:false,maxlength:2000})}<button type="button" id="ticket-followup-send">发送补充 / 追问</button><p class="muted">内容只交给有权限的处理人员。已结束工单收到新问题后会重新进入处理。</p></section><section>${(ticket.reply_feedback||[]).slice(0,2).map(f=>`<h4>${f.action==='auto_replied'?'灯灯自动回复':'工作人员回复'}</h4>${feedbackMarkup('ticket',f.id,f.helpful)}`).join('')}</section></div>`,{wide:true,label:tr('补充附件','Add attachments'),submit:remaining>0?async()=>{const ids=picker.ids();if(!ids.length)throw new Error(tr('请先选择附件','Select an attachment first'));await post('/api/ticket-attachments',{ticket_id:String(ticket.id),attachment_ids:ids});picker.commit();toast(tr('补充材料已保存','Attachments saved'));try{await onChanged();}catch(e){toast(e.message,true);}}:null});
 if(remaining>0)picker=attachmentPicker(dialog,{max:remaining,existingBytes:(ticket.attachments||[]).reduce((sum,f)=>sum+f.size,0)});
 bindFeedback(dialog);$('#ticket-followup-send',dialog).onclick=e=>action(e.currentTarget,async()=>{await post('/api/ticket-updates',{ticket_id:id,kind:$('[name=followup_kind]',dialog).value,content:$('[name=followup_content]',dialog).value});toast('补充已发送');dialog.close();await onChanged();await viewCitizenTicket(id,{onChanged});});
 $('#consent-toggle',dialog).hidden=ticket.private_support;
 $('#consent-toggle',dialog).onclick=e=>action(e.currentTarget,async()=>{await patch('/api/tickets?my=1&id='+encodeURIComponent(id),{public_consent:!ticket.public_consent});dialog.close();await onChanged();await viewCitizenTicket(id,{onChanged});});return dialog;
}

function progressMarkup(t){const stages=[['已提交',true],['处理中',t.status==='in_progress'||!!t.admin_reply],['已回复',!!t.admin_reply],['已结束',['resolved','closed'].includes(t.status)]];return `<ol class="ticket-progress" aria-label="工单进度">${stages.map(([label,done])=>`<li class="${done?'done':''}">${done?'✓ ':'○ '}${label}</li>`).join('')}</ol>`;}
