import {$,$$,api,post,region,tr,esc,text,ticketBody,date,status,field,modal,requirePlayer,action,state} from './core.js';
import {createTicket,viewCitizenTicket,showAdminDirectory,replyAuthor} from './ticket-form.js';
import {newestTicket} from './ticket-preview.js';
export async function renderTicketCenter(el){
 let mode='preview',rows=[],offset=0,hasMore=false,epoch=0;
 el.innerHTML=`<span id="wall"></span><div class="toolbar"><button id="new-ticket" class="primary">＋ ${tr('提交留言 / 工单','New message / ticket')}</button><button id="admin-directory">${tr('查看管理员编号','Administrator IDs')}</button><div class="tabs"><button data-mode="public" aria-selected="false">${tr('公开处理','Public processing')}</button><button data-mode="my" aria-selected="false">${tr('我的工单','My tickets')}</button></div></div><p class="muted">${tr('公开内容经提交者授权和工作人员审核。私密工单与附件不会出现在这里。','Public items require the submitter’s consent and staff review. Private tickets and attachments are not shown here.')}</p><div id="ticket-feed"></div><div class="actions"><button id="ticket-more" hidden>加载更多</button><button id="ticket-collapse" hidden>收起列表</button></div>`;
 function card(t,mine,compact=false){return `<article class="panel ${compact?'ticket-preview':''}"><div class="row-head"><h3>${esc(t.title)}</h3>${status(t.status)}</div>${compact?'':`<div>${ticketBody(t.body)}</div>`}<small>${date(t.created_at)}</small>${!compact&&t.auto_reply?`<div class="notice"><b>${tr('灯灯 · 自动基础回复','DengDeng · Automatic first reply')}</b><p>${text(t.auto_reply)}</p></div>`:''}${!compact&&t.admin_reply?`<div class="notice"><b>${esc(replyAuthor(t))}</b><p>${text(t.admin_reply)}</p></div>`:''}<div class="actions"><button data-ticket="${esc(t.id)}" data-mine="${mine?'1':'0'}">${tr(mine?'办理记录 / 附件':'查看公开详情',mine?'History / attachments':'Public details')}</button>${mine?`<span class="badge">${tr(t.public_visible?'已公开':t.public_consent?'待审核公开':'私密',t.public_visible?'Public':t.public_consent?'Awaiting publication':'Private')}</span>`:''}</div></article>`;}
 function bind(){$$('[data-ticket]',el).forEach(b=>b.onclick=()=>action(b,()=>b.dataset.mine==='1'?viewCitizenTicket(b.dataset.ticket,{onChanged:()=>load(true)}):publicDetails(b.dataset.ticket)));}
 async function preview(){await state.authPending;let ticket=null,mine=false;if(state.session?.player){const result=await Promise.all(['open','in_progress'].map(status=>api('/api/tickets?my=1&status='+status+'&limit=1')));ticket=newestTicket(result.flatMap(d=>d.tickets));mine=!!ticket;}if(!ticket)ticket=(await api('/api/tickets?public=1&limit=1')).tickets[0];return {ticket,mine};}
 async function load(reset=true){const current=++epoch,selected=mode;$('#ticket-more',el).hidden=true;$('#ticket-collapse',el).hidden=selected==='preview';
 if(selected==='preview'){await region($('#ticket-feed',el),preview,(d,box)=>{if(current!==epoch)return;box.innerHTML=d.ticket?card(d.ticket,d.mine,true):`<div class="empty"><p>${tr('暂无已获授权并公开的工单','No authorized public tickets yet')}</p></div>`;bind();});return;}
 const feed=$('#ticket-feed',el);feed._load=Symbol();feed.removeAttribute('aria-busy');if(reset){rows=[];offset=0;feed.innerHTML='<p role="status">正在加载…</p>';}
 try{const d=await api('/api/tickets?'+(selected==='my'?'my=1':'public=1')+'&limit=100&offset='+offset);if(current!==epoch||!el.isConnected)return;rows=[...new Map([...rows,...d.tickets].map(t=>[t.id,t])).values()];offset+=d.tickets.length;hasMore=d.has_more;$('#ticket-feed',el).innerHTML=rows.length?rows.map(t=>card(t,selected==='my')).join(''):`<div class="empty"><p>${tr(selected==='my'?'你还没有工单':'暂无已获授权并公开的工单',selected==='my'?'No tickets yet':'No authorized public tickets yet')}</p></div>`;$('#ticket-more',el).hidden=!hasMore;bind();}catch(error){if(current===epoch){if(reset)feed.innerHTML='<p class="notice">'+esc(error.message)+'</p>';$('#ticket-more',el).hidden=!hasMore;}throw error;}
 }
 async function setMode(next){if(next==='my')await requirePlayer();mode=next;$$('[data-mode]',el).forEach(b=>b.setAttribute('aria-selected',String(b.dataset.mode===mode)));await load(true);}
 $('#new-ticket',el).onclick=e=>action(e.currentTarget,()=>createTicket({kind:'message',onCreated:()=>setMode('my')}));$('#admin-directory',el).onclick=e=>action(e.currentTarget,showAdminDirectory);$$('[data-mode]',el).forEach(b=>b.onclick=()=>action(b,()=>setMode(b.dataset.mode)));$('#ticket-more',el).onclick=e=>action(e.currentTarget,()=>load(false));$('#ticket-collapse',el).onclick=e=>action(e.currentTarget,()=>setMode('preview'));await load();
}
async function publicDetails(id){const {ticket}=await api('/api/tickets?public=1&id='+encodeURIComponent(id));const dialog=modal(ticket.title,`<div class="wide"><p>${status(ticket.status)}</p><p>${text(ticket.body)}</p>${ticket.admin_reply?`<div class="notice"><b>${esc(replyAuthor(ticket))}</b><p>${text(ticket.admin_reply)}</p></div>`:''}<h3>${tr('公开评论','Public comments')}</h3><div id="public-comments"></div></div>`+field('content',tr('添加公开评论','Add a public comment'),'textarea'),{wide:true,label:tr('发表评论','Post comment'),submit:async data=>{await requirePlayer();await post('/api/ticket-comments',{ticket_id:id,content:data.content});}});await region($('#public-comments',dialog),()=>api('/api/ticket-comments?ticket_id='+encodeURIComponent(id)),(d,box)=>box.innerHTML=d.comments.map(c=>`<div class="row"><b>${esc(c.author_name)}</b><p>${text(c.content)}</p><small>${date(c.created_at)}</small></div>`).join('')||`<p class="muted">${tr('暂无评论','No comments')}</p>`);}
