import {endpoint,identity,body,string,integer,reply,fail} from '../../_core/request.js';
import {sourceDocument,digest,fresh,searchKnowledge} from '../../_core/knowledge.js';
const values=b=>({title:string(b.title,'标题',150),question:string(b.question,'适用问题',1000),answer:string(b.answer,'知识正文',4000),keywords:string(b.keywords||'','关键词',300,{required:false})});
export const onRequestGet=c=>endpoint(async()=>{await identity(c,'super');const u=new URL(c.request.url),db=c.env.DB;
 if(u.searchParams.get('action')==='history')return reply({versions:(await db.prepare('SELECT * FROM knowledge_versions WHERE article_id=? ORDER BY revision DESC LIMIT 100').bind(integer(u.searchParams.get('id'))).all()).results});
 if(u.searchParams.get('action')==='sources')return reply({sources:[...(await db.prepare("SELECT id,title,'announcement' AS kind FROM announcements ORDER BY id DESC LIMIT 100").all()).results,...(await db.prepare("SELECT id,title,'license' AS kind FROM license_requirements WHERE is_active=1 ORDER BY id LIMIT 100").all()).results,...(await db.prepare("SELECT id,question AS title,'exam' AS kind FROM exam_questions ORDER BY id LIMIT 100").all()).results,...(await db.prepare("SELECT id,public_title AS title,'ticket' AS kind FROM tickets WHERE public_consent=1 AND public_visible=1 AND status IN ('resolved','closed') AND public_reply IS NOT NULL AND source_table IS NOT 'support' ORDER BY id DESC LIMIT 100").all()).results]});
 if(u.searchParams.get('action')==='test'){const rows=await searchKnowledge(db,string(u.searchParams.get('q'),'测试问题',500));return reply({articles:rows.map(r=>({id:r.id,title:r.title,answer:r.answer,score:r.score})),mode:'public_retrieval',note:'测试只读，不会发送客服回复。'});}
 const limit=100,args=[],clauses=[];if(u.searchParams.has('cursor')){clauses.push('id<?');args.push(integer(u.searchParams.get('cursor')));}if(u.searchParams.get('q')){clauses.push('(title LIKE ? OR question LIKE ?)');args.push('%'+u.searchParams.get('q')+'%','%'+u.searchParams.get('q')+'%');}
 const rows=(await db.prepare(`SELECT * FROM knowledge_articles ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY id DESC LIMIT ?`).bind(...args,limit).all()).results;
 for(const r of rows)r.source_valid=await fresh(db,r);return reply({articles:rows,next_cursor:rows.length===limit?rows.at(-1).id:null});
});
export const onRequestPost=c=>endpoint(async()=>{const admin=await identity(c,'super'),b=await body(c.request),db=c.env.DB,kind=b.source_kind||'manual';let v,sourceId=null,hash=null;
 if(kind==='manual')v=values(b);else{if(!['guide','announcement','license','exam','ticket'].includes(kind))fail(400,'资料来源无效');sourceId=integer(b.source_id);v=await sourceDocument(db,kind,sourceId);if(!v||!v.answer)fail(404,'来源不可用；工单仅支持已办结且审核公开的内容');hash=await digest(v);v={...v,...values(v)};}
 const audience=v.audience||b.audience||'public';if(!['public','staff','exam'].includes(audience))fail(400,'适用范围无效');
 const result=await db.batch([db.prepare("INSERT OR IGNORE INTO knowledge_articles(title,question,answer,keywords,audience,source_kind,source_id,source_hash,created_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(v.title,v.question,v.answer,v.keywords,audience,kind,sourceId,hash,admin.id),db.prepare("INSERT INTO knowledge_versions(article_id,revision,payload,actor_id,actor_name,action) SELECT last_insert_rowid(),1,?,?,?,'created' WHERE changes()=1").bind(JSON.stringify({...v,audience,status:'draft',source_kind:kind,source_id:sourceId,source_hash:hash}),admin.id,admin.username),db.prepare("INSERT INTO audit_events(actor_type,actor_id,actor_name,action,resource_type,resource_id,http_status,details) SELECT 'admin',?,?,'knowledge.draft_created','knowledge_articles',CAST(last_insert_rowid() AS TEXT),201,? WHERE changes()=1").bind(admin.id,admin.username,JSON.stringify({source_kind:kind,source_id:sourceId,audience}))]);
 if(!result[0].meta.changes){const existing=await db.prepare('SELECT id FROM knowledge_articles WHERE source_kind=? AND source_id=?').bind(kind,sourceId).first();return reply({id:existing.id,existing:true});}
 return reply({id:result[0].meta.last_row_id,status:'draft'},201);
});
export const onRequestPatch=c=>endpoint(async()=>{const admin=await identity(c,'super'),b=await body(c.request),db=c.env.DB,id=integer(new URL(c.request.url).searchParams.get('id')),revision=integer(b.revision),old=await db.prepare('SELECT * FROM knowledge_articles WHERE id=?').bind(id).first();if(!old)fail(404,'知识条目不存在');if(old.revision!==revision)fail(409,'资料已被修改，请刷新再审核');
 let v={title:old.title,question:old.question,answer:old.answer,keywords:old.keywords},hash=old.source_hash,audience=old.audience,status='draft';
 if(b.action==='refresh'){const doc=await sourceDocument(db,old.source_kind,old.source_id);if(!doc)fail(404,'来源已失效');v=values(doc);hash=await digest(doc);audience=doc.audience;}
 else if(b.action==='publish'){if(b.confirm_review!==true)fail(400,'请先确认内容、隐私和适用范围已核对');if(!await fresh(db,old))fail(409,'来源已变化，请重新同步并审核');status='published';}
 else if(b.action==='retract')status='retracted';
 else {v=values({...old,...b});audience=b.audience||old.audience;if(!['public','staff','exam'].includes(audience))fail(400,'适用范围无效');if(old.source_kind==='exam'&&audience!=='exam')fail(400,'题库来源不能改为公开客服资料');}
 const r=await db.batch([db.prepare("UPDATE knowledge_articles SET title=?,question=?,answer=?,keywords=?,audience=?,status=?,source_hash=?,reviewed_by=?,revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=?").bind(v.title,v.question,v.answer,v.keywords,audience,status,hash,status==='published'?admin.id:null,id,revision),db.prepare("INSERT INTO knowledge_versions(article_id,revision,payload,actor_id,actor_name,action) SELECT ?,?,?,?,?,? WHERE changes()=1").bind(id,revision+1,JSON.stringify({...v,audience,status,source_hash:hash}),admin.id,admin.username,b.action||'edited'),db.prepare("INSERT INTO audit_events(actor_type,actor_id,actor_name,action,resource_type,resource_id,http_status,details) SELECT 'admin',?,?,?,'knowledge_articles',?,200,? WHERE changes()=1").bind(admin.id,admin.username,'knowledge.'+(b.action||'edited'),String(id),JSON.stringify({from:old.status,to:status,revision:revision+1}))]);if(!r[0].meta.changes)fail(409,'资料已被修改，请刷新');return reply({id,status,revision:revision+1});
});
