import {endpoint,identity,body,string,integer,reply,fail} from '../../_core/request.js';
import {chatAccess} from '../../_core/chat-support.js';
import {getOrCreateAiBot} from '../../_shared/ai.js';
export const onRequestGet=c=>endpoint(async()=>{const a=await identity(c,'admin'),u=new URL(c.request.url),db=c.env.DB;if(u.searchParams.has('id')){const chat=await chatAccess(db,a,integer(u.searchParams.get('id')),{readOnly:true}),bot=await getOrCreateAiBot(c.env);const messages=(await db.prepare('SELECT * FROM (SELECT d.id,d.from_player_id,d.to_player_id,d.content,d.created_at,d.replied_by_admin_id,ad.username AS reply_author_name FROM direct_messages d LEFT JOIN admins ad ON ad.id=d.replied_by_admin_id WHERE ((d.from_player_id=? AND d.to_player_id=?) OR (d.from_player_id=? AND d.to_player_id=?)) AND EXISTS(SELECT 1 FROM support_chats live WHERE live.id=? AND (?=\'super\' OR live.requires_super=0)) ORDER BY d.id DESC LIMIT 200) ORDER BY id').bind(chat.player_id,bot.id,bot.id,chat.player_id,chat.id,a.role).all()).results;return reply({chat:{...chat,is_self:a.linked_player_id===chat.player_id,player_name:(await db.prepare('SELECT username FROM players WHERE id=?').bind(chat.player_id).first()).username},messages,events:(await db.prepare('SELECT * FROM support_chat_events WHERE chat_id=? ORDER BY id').bind(chat.id).all()).results});}
 const rows=(await db.prepare("SELECT c.*,p.username,a.username AS admin_name,(SELECT content FROM direct_messages d WHERE d.from_player_id=c.player_id AND d.to_player_id=(SELECT id FROM players WHERE username='灯灯客服' AND game_id='AI_BOT') ORDER BY d.id DESC LIMIT 1) AS last_question FROM support_chats c JOIN players p ON p.id=c.player_id LEFT JOIN admins a ON a.id=c.assigned_admin_id WHERE (?='super' OR c.requires_super=0) ORDER BY CASE c.status WHEN 'queued' THEN 0 WHEN 'active' THEN 1 ELSE 2 END,c.updated_at DESC LIMIT 100").bind(a.role).all()).results;return reply({chats:rows.map(r=>({...r,is_self:r.player_id===a.linked_player_id}))});});
export const onRequestPost=c=>endpoint(async()=>{const a=await identity(c,'admin'),b=await body(c.request),db=c.env.DB,chat=await chatAccess(db,a,integer(b.id)),action=b.action;
 if(action==='claim'){if(chat.status==='active'&&chat.assigned_admin_id===a.id)return reply({claimed:true});if(chat.status!=='queued')fail(409,'会话已被接入或已结束');const r=await db.batch([db.prepare("UPDATE support_chats SET status='active',assigned_admin_id=?,revision=revision+1,updated_at=datetime('now') WHERE id=? AND status='queued'").bind(a.id,chat.id),db.prepare("INSERT INTO support_chat_events(chat_id,actor_type,actor_id,actor_name,action) SELECT ?,'admin',?,?,'claimed' WHERE changes()=1").bind(chat.id,a.id,a.username)]);if(!r[0].meta.changes)fail(409,'其他客服已接入');return reply({claimed:true});}
 if(chat.status!=='active'||chat.assigned_admin_id!==a.id&&a.role!=='super')fail(403,'请由已接入客服处理此会话');const revision=integer(b.revision,'会话版本',1);if(chat.revision!==revision)fail(409,'会话已更新，请刷新');let content='',summary='';
 if(action==='reply')content=string(b.content,'回复',2000);else if(action==='suggest-ticket')summary=string(b.summary,'给玩家的工单说明',2000);else if(action!=='close')fail(400,'操作无效');
 const bot=await getOrCreateAiBot(c.env),update=action==='close'?"status='closed'":action==='suggest-ticket'?"needs_ticket=1,ticket_summary=?":"status='active'";
 const ops=[db.prepare(`UPDATE support_chats SET ${update},revision=revision+1,updated_at=datetime('now') WHERE id=? AND revision=? AND status='active'`).bind(...(action==='suggest-ticket'?[summary]:[]),chat.id,revision),db.prepare("INSERT INTO support_chat_events(chat_id,actor_type,actor_id,actor_name,action,details) SELECT ?,'admin',?,?,?,? WHERE changes()=1").bind(chat.id,a.id,a.username,action,JSON.stringify(action==='reply'?{reply:content}:action==='suggest-ticket'?{summary}:{}))];
 if(action==='reply'||action==='suggest-ticket')ops.push(db.prepare('INSERT INTO direct_messages(from_player_id,to_player_id,content,replied_by_admin_id) SELECT ?,?,?,? WHERE changes()=1').bind(bot.id,chat.player_id,action==='reply'?content:'这个问题需要通过工单继续处理。你可以点击本会话上方的“提交工单”，检查说明后确认提交。',a.id));
 ops.push(db.prepare("INSERT INTO notification_log(player_id,type,title,body,link) SELECT ?,'support_chat','人工客服有更新','请在灯灯会话中查看回复。','/dm.html?to=%E7%81%AF%E7%81%AF%E5%AE%A2%E6%9C%8D' WHERE changes()=1").bind(chat.player_id),db.prepare("INSERT INTO audit_events(actor_type,actor_id,actor_name,action,resource_type,resource_id,http_status,details) SELECT 'admin',?,?,?,'support_chats',?,200,? WHERE changes()=1").bind(a.id,a.username,'support.'+action,String(chat.id),JSON.stringify({action})));
 const r=await db.batch(ops);if(!r[0].meta.changes)fail(409,'会话已由其他工作人员更新，请刷新');return reply({saved:true});});
